name = "LeanLangur"
version = "0.1.0"
keywords = ["math"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "Blaster"
git = "https://github.com/kayceesrk/Lean-blaster"
rev = "chore-bump-lean-4.28"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "CaseStudies"
