name = "LeanLangur"
version = "0.1.0"
keywords = ["math"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "Blaster"
git = "https://github.com/input-output-hk/Lean-blaster"
rev = "main"

[[require]]
name = "smt"
scope = "ufmg-smite"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
<<<<<<< HEAD
rev = "v4.26.0"
=======
rev = "v4.28.0"
>>>>>>> 0044841 (rebased with main)

[[lean_lib]]
name = "CaseStudies"
