import Sal.MRDTs.Paper1.ExecutionTrace
import Sal.MRDTs.Paper1.AnchoredQueueCommutation
import Sal.MRDTs.Paper1.AnchoredQueueSupport
import Sal.MRDTs.Paper1.AnchoredQueueRanks
import Sal.MRDTs.Paper1.AnchoredQueueSurvivors

/-! Assembly of the single independent FIFO witness. Its deletion blocks are
 generated by the executable scheduler; the live suffix retains all tagged
 identities, so the unchanged public tagged-head query follows directly. -/
namespace Sal.MRDTs.Paper1.AnchoredQueue.History
open Foundation Instances.EmbedRGA

/-- Every specified causal conflict is respected by the generated deletion
 prefix and the surviving birth suffix of the same word. -/
theorem schedule_conflict_order (C : Configuration Q) (H : Set Event)
    (ps : List BirthDelete) (live : List Event)
    (freshRanks : FreshRanks (deadRank H) [] ps)
    (deletionRanks : ∀ p ∈ ps, deadRank H p.deletion = 2 * p.deletion.time + 1)
    (chronological : ps.Pairwise (fun p q => p.deletion.time < q.deletion.time))
    (deadIncreases : ∀ a ∈ deadWord [] ps, ∀ b ∈ deadWord [] ps,
      C.vis a b ∧ Conflict a b → deadRank H a < deadRank H b)
    (liveOrder : respects live C.vis)
    (cross : ∀ a ∈ deadWord [] ps, ∀ b ∈ live, ¬ (C.vis b a ∧ Conflict b a)) :
    respects (deadWord [] ps ++ live) (fun a b => C.vis a b ∧ Conflict a b) := by
  apply List.pairwise_append.mpr
  refine ⟨deadWord_respects (deadRank H) [] ps _ freshRanks deletionRanks
    chronological deadIncreases, liveOrder.imp ?_,?_⟩
  · intro a b absent edge
    exact absent edge.1
  · exact cross

theorem dead_live_cross {C : Configuration Q} {H : Set Event}
    (execution : CertifiedExecution Q issuance C)
    (closed : ∀ a b, C.vis a b → b ∈ H → a ∈ H)
    (support : H ⊆ C.events) (dead : DeadEndpoint C H)
    (live : List Event)
    (liveSupport : ∀ e ∈ live, e ∈ H)
    (insertions : ∀ e ∈ live, eIsIns e = true)
    (surviving : ∀ e ∈ live, ¬ HasDeletion H e) :
    ∀ a ∈ deadWord [] dead.pairs, ∀ b ∈ live, ¬ (C.vis b a ∧ Conflict b a) := by
  intro a ha b hb edge
  have aSupport := dead.word_support support ha
  have bSupport := liveSupport b hb
  have bInsertion := insertions b hb
  have bSurviving := surviving b hb
  have removed := dead.word_birth_removed support ha
  rcases b with ⟨bt,br,bo⟩
  cases bo with
  | del target => simp [eIsIns] at bInsertion
  | ins value coordinate anchor =>
    rcases a with ⟨ta,ra,oa⟩
    cases oa with
    | ins value' coordinate' anchor' =>
      apply bSurviving
      apply (hasDeletion_iff H _).mpr
      exact removed_births_causal_downset execution closed support
        (support bSupport) (support aSupport) rfl rfl edge.1
        ((hasDeletion_iff H _).mp (removed rfl))
    | del target =>
      have time : bt = target := edge.2
      apply bSurviving
      exact ⟨ta,(ta,ra,.del target),aSupport,by
        simp only [Op.op,Op.time]
        rw [time],rfl⟩

theorem endpoint_coverage {C : Configuration Q} {H : Set Event}
    (support : H ⊆ C.events) (dead : DeadEndpoint C H) (live : List Event)
    (liveSupport : ∀ e ∈ live, e ∈ H)
    (complete : ∀ e ∈ H, eIsIns e = true → ¬ HasDeletion H e → e ∈ live) :
    ∀ e, e ∈ H ↔ (∃ p ∈ dead.pairs, e = p.birth ∨ e = p.deletion) ∨ e ∈ live := by
  intro e
  constructor
  · intro member
    by_cases insertion : eIsIns e = true
    · by_cases removed : HasDeletion H e
      · obtain ⟨p,hp,same⟩ := dead.removed_birth_complete support member insertion removed
        exact Or.inl ⟨p,hp,Or.inl same.symm⟩
      · exact Or.inr (complete e member insertion removed)
    · have deletion : eIsIns e = false := Bool.eq_false_iff.mpr insertion
      obtain ⟨p,hp,same⟩ := dead.complete e member deletion
      exact Or.inl ⟨p,hp,Or.inr same.symm⟩
  · rintro (⟨p,hp,rfl | rfl⟩ | liveMember)
    · exact dead.birthSupport p hp
    · exact dead.deletionSupport p hp
    · exact liveSupport e liveMember

theorem endpoint_separated {C : Configuration Q} {H : Set Event}
    (dead : DeadEndpoint C H) (live : List Event)
    (insertions : ∀ e ∈ live, eIsIns e = true)
    (surviving : ∀ e ∈ live, ¬ HasDeletion H e) :
    ∀ e ∈ live, ∀ p ∈ dead.pairs, e ≠ p.birth ∧ e ≠ p.deletion := by
  intro e he p hp
  constructor
  · intro same
    apply surviving e he
    rw [same]
    exact ⟨p.deletion.time,p.deletion,dead.deletionSupport p hp,p.target,rfl⟩
  · intro same
    have insertion := insertions e he
    rw [same] at insertion
    have target := p.target
    simp only [eIsIns,Op.op] at target insertion
    rw [target] at insertion
    contradiction

structure PublicWitness (C : Configuration Q) (s : State) (H : Set Event) where
  word : List Event
  perm : listPermOf word H
  conflictOrder : respects word (fun a b => C.vis a b ∧ Conflict a b)
  legal : fifoLegal word
  representation : s.map (fun r => (r.1,r.2.1)) = fifoFold word

/-- The generated word is legal, enumerates every original event exactly
 once and has the exact final tagged live list. -/
theorem schedule_publicWitness {C : Configuration Q} {s : State} {H : Set Event}
    (ps : List BirthDelete) (live : List Event)
    (pairs : pairSupport C.events ps)
    (deletions : (ps.map BirthDelete.deletion).Nodup)
    (liveNodup : live.Nodup)
    (liveSupport : ∀ e ∈ live, e ∈ C.events)
    (insertions : ∀ e ∈ live, eIsIns e = true)
    (separated : ∀ e ∈ live, ∀ p ∈ ps, e ≠ p.birth ∧ e ≠ p.deletion)
    (coverage : ∀ e, e ∈ H ↔ (∃ p ∈ ps, e = p.birth ∨ e = p.deletion) ∨ e ∈ live)
    (freshRanks : FreshRanks (deadRank H) [] ps)
    (deletionRanks : ∀ p ∈ ps, deadRank H p.deletion = 2 * p.deletion.time + 1)
    (chronological : ps.Pairwise (fun p q => p.deletion.time < q.deletion.time))
    (deadIncreases : ∀ a ∈ deadWord [] ps, ∀ b ∈ deadWord [] ps,
      C.vis a b ∧ Conflict a b → deadRank H a < deadRank H b)
    (liveOrder : respects live C.vis)
    (cross : ∀ a ∈ deadWord [] ps, ∀ b ∈ live, ¬ (C.vis b a ∧ Conflict b a))
    (representation : s.map (fun r => (r.1,r.2.1)) = live.map birthTag) :
    Nonempty (PublicWitness C s H) := by
  have unique : ∀ a ∈ C.events, ∀ b ∈ C.events, a.time = b.time → a = b :=
    fun _ ha _ hb eq => C.replayContext.ts_unique ha hb eq
  have distinct : live.Pairwise (fun a b => a.time ≠ b.time) := by
    apply liveNodup.pairwise_of_forall_ne
    intro a ha b hb different same
    exact different (unique a (liveSupport a ha) b (liveSupport b hb) same)
  refine ⟨⟨deadWord [] ps ++ live,
    schedule_listPermOf unique ps live pairs deletions liveNodup separated coverage,
    schedule_conflict_order C H ps live freshRanks deletionRanks chronological
      deadIncreases liveOrder cross,
    schedule_legal ps live insertions distinct
      (surviving_fresh unique ps live pairs liveSupport separated),?_⟩⟩
  rw [schedule_fold ps live insertions]
  exact representation

theorem kernel_versions_of_witnesses {C : Configuration Q}
    (execution : CertifiedExecution Q issuance C)
    (witnesses : ∀ v s H, C.ver v = some (s,H) → Nonempty (PublicWitness C s H)) :
    InvariantOrder.VersionsRA Q (Valid C)
      CertifiedRGAInvariantReplay.policy language C := by
  apply versions_of_witnesses
  intro v s H stored
  obtain ⟨w⟩ := witnesses v s H stored
  have good := CertifiedRGAExecution.Embedded.canonicalConfig
    Sal.EmbedRGA.unaryCode (execution_weaken execution)
  refine ⟨⟨w.word,w.perm,?_,?_,w.legal,w.representation⟩⟩
  · apply w.conflictOrder.imp_of_mem
    intro a b ha hb absent edge
    have haC := good.version_events_supported v s H stored a ((w.perm.2 a).mp ha)
    have hbC := good.version_events_supported v s H stored b ((w.perm.2 b).mp hb)
    exact absent (invariant_order_conflict execution hbC haC edge)
  · apply w.conflictOrder.imp
    intro a b absent edge
    exact absent (visibility_conflict edge)

/-- Strong exact tagged-state witnesses imply the original public tagged-head
 criterion on ordinary and recursive virtual configurations alike. -/
theorem public_versions_of_witnesses {C : Configuration publicQueue}
    (execution : CertifiedExecution publicQueue Public.issuance C)
    (witnesses : ∀ v s H, C.ver v = some (s,H) →
      Nonempty (PublicWitness (Public.kernel C) s H)) :
    InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel C))
      CertifiedRGAInvariantReplay.policy Public.language C := by
  intro v s H stored q
  obtain ⟨w⟩ := witnesses v s H stored
  have exec := Public.execution execution
  refine ⟨w.word,w.perm,?_,?_,?_⟩
  · apply w.conflictOrder.imp_of_mem
    intro a b ha hb absent edge
    have supported := CertifiedRGAExecution.Embedded.canonicalConfig
      Sal.EmbedRGA.unaryCode (execution_weaken exec)
    have haC : a ∈ (Public.kernel C).events := by
      exact supported.version_events_supported v s H stored a ((w.perm.2 a).mp ha)
    have hbC : b ∈ (Public.kernel C).events := by
      exact supported.version_events_supported v s H stored b ((w.perm.2 b).mp hb)
    exact absent (invariant_order_conflict exec hbC haC edge)
  · apply w.conflictOrder.imp
    intro a b absent edge
    exact absent (public_visibility_conflict edge)
  · have answer : publicQueue.query s q = Public.fifoSpec.query
        (Public.fifoSpec.run w.word) q := by
      change s.head?.map (fun r => (r.1,r.2.1)) = (fifoFold w.word).head?
      rw [← w.representation]
      simp
    rw [answer]
    exact GuardedHistory.admits_updates_query Public.fifoSpec
      (fun _ _ h => fifoLegal_prefix h) w.word w.legal q

/-- Every stored version obtains the same explicitly constructed independent
 FIFO word, using certified head/tail issuance and represented live records. -/
theorem stored_publicWitness {C : Configuration Q}
    (execution : CertifiedExecution Q issuance C) {v : Version} {s : State} {H : Set Event}
    (stored : C.ver v = some (s,H)) : Nonempty (PublicWitness C s H) := by
  have good := CertifiedRGAExecution.Embedded.canonicalConfig
    Sal.EmbedRGA.unaryCode (execution_weaken execution)
  have support : H ⊆ C.events := good.version_events_supported v s H stored
  have closed : ∀ a b, C.vis a b → b ∈ H → a ∈ H :=
    good.version_events_causal v s H stored
  obtain ⟨ops,perm,_,_⟩ := good.canonical v s H stored
  obtain ⟨dead⟩ := exists_deadEndpoint execution closed support ⟨ops,perm⟩
  let live := liveEndpoint execution stored
  apply schedule_publicWitness dead.pairs live.live
    (fun p hp => ⟨support (dead.birthSupport p hp),support (dead.deletionSupport p hp)⟩)
    dead.deletions_nodup live.nodup
    (fun e he => support (live.support e he)) live.insertions
    (endpoint_separated dead live.live live.insertions live.surviving)
    (endpoint_coverage support dead live.live live.support live.complete)
    dead.freshRanks dead.deletionRanks dead.chronological
    (fun a ha b hb edge => dead.causalRanks execution closed support ha hb edge.1 edge.2)
    live.causalOrder
    (fun a ha b hb => dead.no_survivor_predecessor execution closed support
      (live.support b hb) (live.insertions b hb) (live.surviving b hb) ha)
    live.representation

theorem versions {C : Configuration Q} (execution : CertifiedExecution Q issuance C) :
    InvariantOrder.VersionsRA Q (Valid C) CertifiedRGAInvariantReplay.policy language C :=
  kernel_versions_of_witnesses execution (fun _ _ _ stored => stored_publicWitness execution stored)

/-- The public observation remains the original tagged head. This root accepts
 both ordinary executions and recursive virtual-base executions with no
 additional history, replay or scheduling hypothesis. -/
theorem public_versions {C : Configuration publicQueue}
    (execution : CertifiedExecution publicQueue Public.issuance C) :
    InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel C))
      CertifiedRGAInvariantReplay.policy Public.language C :=
  public_versions_of_witnesses execution
    (fun _ _ _ stored => stored_publicWitness (Public.execution execution) stored)

theorem correct {C : Configuration publicQueue}
    (reach : MintCertifiedReach publicQueue Public.issuance C) :
    InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel C))
      CertifiedRGAInvariantReplay.policy Public.language C := public_versions (.ordinary reach)

theorem correctV {C : Configuration publicQueue}
    (reach : MintCertifiedReachV publicQueue (canonicalVirtualMergeBase publicQueue)
      Public.issuance C) :
    InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel C))
      CertifiedRGAInvariantReplay.policy Public.language C := public_versions (.virtual reach)

theorem executions (trace : List (Label publicQueue × Configuration publicQueue))
    (run : (certifiedTS publicQueue Public.issuance).Execution (initConfig publicQueue) trace) :
    InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel (initConfig publicQueue)))
      CertifiedRGAInvariantReplay.policy Public.language (initConfig publicQueue) ∧
    ∀ entry ∈ trace, InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel entry.2))
      CertifiedRGAInvariantReplay.policy Public.language entry.2 := by
  have reached := ExecutionTrace.visited (Good := MintCertifiedReach publicQueue Public.issuance)
    (fun _ _ _ pre step => .step pre step.1 step.2.1 step.2.2) run .init
  exact ⟨correct .init,fun entry member => correct (reached entry member)⟩

theorem executionsV (trace : List (Label publicQueue × Configuration publicQueue))
    (run : (certifiedTSV publicQueue Public.issuance).Execution (initConfig publicQueue) trace) :
    InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel (initConfig publicQueue)))
      CertifiedRGAInvariantReplay.policy Public.language (initConfig publicQueue) ∧
    ∀ entry ∈ trace, InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel entry.2))
      CertifiedRGAInvariantReplay.policy Public.language entry.2 := by
  have reached := ExecutionTrace.visited (Good := MintCertifiedReachV publicQueue
      (canonicalVirtualMergeBase publicQueue) Public.issuance)
    (fun _ _ _ pre step => .step pre step.1 step.2.1 step.2.2) run .init
  exact ⟨correctV .init,fun entry member => correctV (reached entry member)⟩

/-- The independent FIFO bridge accompanies the implementation's separately
 justified representation closure and restricted replay VCs. -/
structure Certificate (C : Configuration publicQueue) : Prop where
  closed : InvariantOrder.Closed publicQueue C.replayContext (Valid (Public.kernel C))
  stored_valid : ∀ v s H, C.ver v = some (s,H) → Valid (Public.kernel C) s
  scoped_replay : ∀ v s H, C.ver v = some (s,H) →
    InvariantReplay.RestrictedLaws
      (CertifiedRGAInvariantReplay.scope Sal.EmbedRGA.unaryCode (Public.kernel C) H)
      (Valid (Public.kernel C)) CertifiedRGAInvariantReplay.policy ∧
    InvariantReplay.Canonical
      (CertifiedRGAInvariantReplay.scope Sal.EmbedRGA.unaryCode (Public.kernel C) H)
      (Valid (Public.kernel C)) CertifiedRGAInvariantReplay.policy publicQueue.init s
  virtual_valid : ∀ v w s t H K, C.ver v = some (s,H) → C.ver w = some (t,K) →
    Valid (Public.kernel C) (virtualMergeBaseState C v w)
  versions : InvariantOrder.VersionsRA publicQueue (Valid (Public.kernel C))
    CertifiedRGAInvariantReplay.policy Public.language C

theorem certificate {C : Configuration publicQueue}
    (execution : CertifiedExecution publicQueue Public.issuance C) : Certificate C := by
  have kernelExec := Public.execution execution
  have kernelClosed := AnchoredQueue.closed kernelExec
  refine ⟨⟨kernelClosed.initial,kernelClosed.update,kernelClosed.merge⟩,
    fun _ _ _ stored => AnchoredQueue.stored_valid kernelExec stored,
    fun _ _ _ stored => ⟨AnchoredQueue.scoped_laws kernelExec stored,?_⟩,
    ?_,public_versions execution⟩
  · exact CertifiedRGAInvariantReplay.storedCanonical Sal.EmbedRGA.unaryCode
      (execution_weaken kernelExec) stored
  · intro v w s t H K left right
    rw [← Public.virtual_base]
    exact AnchoredQueue.virtual_base_valid kernelExec left right

#print axioms certificate
#print axioms correct
#print axioms correctV
#print axioms executions
#print axioms executionsV

end Sal.MRDTs.Paper1.AnchoredQueue.History
