import Sal.MRDTs.Paper1.Soundness
import Sal.MRDTs.Paper1.Capstone
import Sal.MRDTs.Paper1.ORSetSPOT
import Sal.MRDTs.Paper1.ORSetSpecification
import Sal.MRDTs.Paper1.ORSetExecution
import Sal.MRDTs.Paper1.CriterionCounterexample
import Sal.MRDTs.Paper1.RGAActive
import Sal.MRDTs.Paper1.RGAStrict
import Sal.MRDTs.Paper1.RGAConflict
import Sal.MRDTs.Paper1.RGAComparison
import Sal.MRDTs.Paper1.RGAEventSpec
import Sal.MRDTs.Paper1.CommutationBridge
import Sal.MRDTs.Paper1.MigrationCoverage
import Sal.MRDTs.Paper1.ORSetBridgeControls
import Mathlib.Util.AssertNoSorry

/-!
# Paper1 theorem and trust ledger

The active manuscript criterion and the stronger specification-visible candidate remain
distinct. Both operation-only RGA languages have full honestly certified
counterexamples from the initial store, excluding all witness orders and
allocation choices. Explicit insertion-ID labels give general positive
guarantees for the same concrete datatype and issuer. These names are the
stable evidence boundary for the canonical task list's research results.
The agreed full-input RGA language retains timestamp, replica, and operation;
its literal and stronger guarantees are recorded under `RGA.EventSpec`.
-/

namespace Sal.MRDTs.Paper1

#check HistorySpec
#check HistoryMachine.toSpec
#check OperationPolicy
#check RestrictedLaws
#check paperOrder
#check RALinearizable
#check RAExecution
#check RAImplementation
#check UniformVersionsRALinearizable
#check CertifiedRA
#check CertifiedRAV
#check PaperMergeVCs
#check SequentialSimulation
#check IssuedHistoryAdequacy
#check SpecificationRALinearizable

-- Audit all load-bearing bridges and the positive/negative research results.
-- Only Lean's standard classical/extensional axioms are permitted.
open Lean Elab Command in
elab "assert_paper_axioms " n:ident : command => do
  let name ← liftCoreM <| Lean.Elab.realizeGlobalConstNoOverloadWithInfo n
  let axioms ← Lean.collectAxioms name
  for axiomName in axioms do
    unless [``propext, ``Classical.choice, ``Quot.sound].contains axiomName do
      throwError "{n} depends on unexpected axiom {axiomName}"

assert_paper_axioms HistoryMachine.toSpec
assert_paper_axioms DeterministicSpec.updates_query_iff
assert_paper_axioms RestrictedLaws.replayLaws
assert_paper_axioms paperOrder_iff_loOn
assert_paper_axioms SequentialSimulation.sound
assert_paper_axioms ra_of_replay_total
assert_paper_axioms uniform_ra_of_replay_total
assert_paper_axioms ra_of_canonical_history
assert_paper_axioms certifiedRA_of_fiveVCs
assert_paper_axioms certifiedRA_of_fiveVCs_issued
assert_paper_axioms certified_convergence_of_join
assert_paper_axioms CertifiedRA.executions
assert_paper_axioms CertifiedRAV.executions
assert_paper_axioms rawRA_of_join_total
assert_paper_axioms specificationRA_of_canonical_total
assert_paper_axioms specificationCertifiedRA_of_join_issued
assert_paper_axioms ORSet.join
assert_paper_axioms ORSet.certifiedRA
assert_paper_axioms ORSet.certifiedRAV
assert_paper_axioms ORSet.specificationCertifiedRA
assert_paper_axioms ORSet.specificationCertifiedRAV
assert_paper_axioms ORSet.rawRA
assert_paper_axioms ORSet.rawUniformRA
assert_paper_axioms ORSet.rawSpecificationRA
assert_paper_axioms ORSet.SPOT.defeater_union
assert_paper_axioms ORSet.Execution.defeater_execution
assert_paper_axioms ORSet.Execution.defeater_ra_execution
assert_paper_axioms ORSet.Execution.defeater_final_ra
assert_paper_axioms ORSet.Execution.figure_states
assert_paper_axioms ORSet.Execution.figure_observations
assert_paper_axioms CriterionCounterexample.bad_execution
assert_paper_axioms CriterionCounterexample.bad_mintCertified
assert_paper_axioms CriterionCounterexample.bad_ra_execution
assert_paper_axioms CriterionCounterexample.criteria_differ_on_reachable_mutation
assert_paper_axioms CriterionCounterexample.mutant_join
assert_paper_axioms CriterionCounterexample.mutant_rawRA
assert_paper_axioms CriterionCounterexample.raw_replay_witness
assert_paper_axioms CriterionCounterexample.raw_store_convergence
assert_paper_axioms CriterionCounterexample.raw_cross_store_convergence
assert_paper_axioms CriterionCounterexample.canonical_reachableV
assert_paper_axioms CriterionCounterexample.virtual_store_convergence
assert_paper_axioms RGA.certifiedRA
assert_paper_axioms RGA.certifiedRAV
assert_paper_axioms RGA.old_list_run_does_not_factor
assert_paper_axioms RGA.Strict.crossed_orders_stuck
assert_paper_axioms RGA.Strict.crossed_no_continuation
assert_paper_axioms RGA.Strict.Trace.local_issuance
assert_paper_axioms RGA.Strict.Trace.merged_effects
assert_paper_axioms RGA.root_insert_remove_not_commute
assert_paper_axioms RGA.anchor_two_insert_remove_one_not_commute
assert_paper_axioms RGA.anchor_one_insert_remove_two_not_commute
assert_paper_axioms RGA.specification_conflicts_not_covered
assert_paper_axioms projected_original_iff
assert_paper_axioms projected_certified_executions
assert_paper_axioms projected_certified_executionsV
assert_paper_axioms RGA.Strict.Investigation.crossed_no_history
assert_paper_axioms RGA.Strict.Investigation.crossed_not_specificationRA
assert_paper_axioms RGA.Strict.Investigation.six_event_no_history
assert_paper_axioms RGA.Strict.Investigation.six_event_primary_escape
assert_paper_axioms RGA.CrossedExecution.execution
assert_paper_axioms RGA.CrossedExecution.Evidence.mint_honest
assert_paper_axioms RGA.CrossedExecution.Evidence.mint_certified
assert_paper_axioms RGA.CrossedExecution.Evidence.observed_execution
assert_paper_axioms RGA.CrossedExecution.Evidence.final_read
assert_paper_axioms RGA.CrossedExecution.Evidence.strict_failure
assert_paper_axioms RGA.CrossedExecution.Evidence.not_every_certified_strict
assert_paper_axioms RGA.Identified.canonical_respects_specVisibility
assert_paper_axioms RGA.Identified.versions_of_execution
assert_paper_axioms RGA.Identified.projection_does_not_factor
assert_paper_axioms RGA.Identified.certifiedStrictRA
assert_paper_axioms RGA.Identified.certifiedStrictRAV
assert_paper_axioms RGA.Identified.certifiedMissingNoopRA
assert_paper_axioms RGA.Identified.certifiedMissingNoopRAV
assert_paper_axioms RGA.Identified.certifiedStrictExecutions
assert_paper_axioms RGA.Identified.certifiedStrictExecutionsV
assert_paper_axioms RGA.Comparison.strict_alphabet_comparison
assert_paper_axioms RGA.Comparison.identified_missing_noop
assert_paper_axioms RGA.AllocatingInvestigation.transition_projects
assert_paper_axioms RGA.AllocatingInvestigation.runs_project
assert_paper_axioms RGA.AllocatingInvestigation.projected_crossed_exclusion
assert_paper_axioms RGA.AllocatingInvestigation.crossed_no_history
assert_paper_axioms RGA.AllocatingCounterexample.not_specificationRA
assert_paper_axioms RGA.AllocatingCounterexample.certified_counterexample
assert_paper_axioms RGA.Comparison.allocating_alphabet_comparison
assert_paper_axioms RGA.Comparison.not_every_certified_allocating
assert_paper_axioms RGA.Comparison.same_execution_comparison
assert_paper_axioms HistorySpec.withInputs_commutes_iff
assert_paper_axioms HistoryMachine.toSpec_withInputs
assert_paper_axioms projected_withInputs
assert_paper_axioms EventSpecificationRALinearizable.active
assert_paper_axioms RGA.EventSpec.insertion_uses_timestamp
assert_paper_axioms RGA.EventSpec.deletion_uses_target
assert_paper_axioms RGA.EventSpec.replica_independent
assert_paper_axioms RGA.EventSpec.commutes_iff
assert_paper_axioms RGA.EventSpec.versions_of_execution
assert_paper_axioms RGA.EventSpec.certifiedRA
assert_paper_axioms RGA.EventSpec.certifiedRAV
assert_paper_axioms RGA.EventSpec.certifiedLiteralRA
assert_paper_axioms RGA.EventSpec.certifiedLiteralRAV
assert_paper_axioms RGA.EventSpec.certifiedMissingRA
assert_paper_axioms RGA.EventSpec.certifiedMissingRAV
assert_paper_axioms RGA.EventSpec.certifiedExecutions
assert_paper_axioms RGA.EventSpec.certifiedExecutionsV
assert_paper_axioms RGA.EventSpec.crossed_accepted
assert_paper_axioms RGA.EventSpec.supplied_inputs_control
assert_paper_axioms commutationCompatibility_iff_conflictsCovered
assert_paper_axioms projectedSpecVisibility_sub_paperOrder
assert_paper_axioms eventSpecificationRA_of_compatibility
assert_paper_axioms specificationRA_of_fiveVCs_compatible
assert_paper_axioms ORSet.commutationCompatibility
assert_paper_axioms ORSet.eventCommutationCompatibility
assert_paper_axioms CriterionCounterexample.commutationCompatibility_fails

-- Full-input bridge: total simulation and both mint/trace-sensitive routes.
assert_paper_axioms restricted_of_all_commute
assert_paper_axioms EventSequentialSimulation.fold_rel
assert_paper_axioms EventSequentialSimulation.sound
assert_paper_axioms EventVersionsSpecificationRA.heads
assert_paper_axioms event_versions_of_canonical_total
assert_paper_axioms event_versions_of_canonical_issued
assert_paper_axioms event_versions_of_canonical_execution
assert_paper_axioms EventCertifiedSpecificationRAV.ordinary
assert_paper_axioms event_certified_of_join_total
assert_paper_axioms event_certified_of_join_issued
assert_paper_axioms event_certified_of_join_execution
assert_paper_axioms event_certified_of_fiveVCs_total
assert_paper_axioms event_certified_of_fiveVCs_issued
assert_paper_axioms event_certified_of_fiveVCs_execution
assert_paper_axioms EventCertifiedSpecificationRA.executions
assert_paper_axioms EventCertifiedSpecificationRAV.executions
assert_paper_axioms GuardedHistory.updates_run
assert_paper_axioms GuardedHistory.admits_updates_query
assert_paper_axioms GuardedHistory.recorded_prefix
assert_paper_axioms GuardedHistory.rejects_first_update
assert_paper_axioms event_versions_of_guarded_certificate

-- Independent specifications and positive/negative controls.
assert_paper_axioms ORSet.EventSpec.certifiedVersionsRAV
assert_paper_axioms ORSet.EventSpec.certifiedExecutionsV
assert_paper_axioms ORSet.EventSpec.rawRA
assert_paper_axioms RGA.EventMigration.history
assert_paper_axioms RGA.EventMigration.certifiedV
assert_paper_axioms RGA.EventMigration.executionsV
assert_paper_axioms RGA.EventMigration.crossed_control
assert_paper_axioms SimpleEventPorts.Add.certifiedV
assert_paper_axioms SimpleEventPorts.Finite.certifiedV
assert_paper_axioms SimpleEventPorts.Boolean.certifiedV
assert_paper_axioms SimpleEventPorts.Delta.certifiedV
assert_paper_axioms SimpleEventPorts.add_control
assert_paper_axioms SimpleEventPorts.finite_add_control
assert_paper_axioms SimpleEventPorts.boolean_control
assert_paper_axioms SimpleEventPorts.immutable_map_control
assert_paper_axioms SimpleEventPorts.increment_control
assert_paper_axioms SimpleEventPorts.pn_control
assert_paper_axioms BoundedCounterEvent.certifiedV
assert_paper_axioms BoundedCounterEvent.account_control
assert_paper_axioms BoundedCounterEvent.initial_decrement_rejected
assert_paper_axioms BoundedCounterEvent.commutationCompatibility_fails
assert_paper_axioms TreeMoveEvent.certifiedV
assert_paper_axioms TreeMoveEvent.origin_control
assert_paper_axioms AegisSheetEvent.certifiedV
assert_paper_axioms AegisSheetEvent.origin_control
assert_paper_axioms EfficientORSet.EventSpec.certifiedVersionsRAV
assert_paper_axioms EfficientORSet.EventSpec.certifiedExecutionsV
assert_paper_axioms EfficientORSet.EventSpec.noncommutation_does_not_factor
assert_paper_axioms EfficientORSet.EventSpec.restrictedLaws_impossible
assert_paper_axioms ORSetBridgeControls.exact_remove_control
assert_paper_axioms ORSetBridgeControls.efficient_remove_control
assert_paper_axioms ORSetBridgeControls.mutant_causal_control
assert_paper_axioms ORSetBridgeControls.mutant_compatibility_fails
assert_paper_axioms ORSetBridgeControls.compatibility_controls

-- Exact production scope, including independently checked incompatibilities.
assert_paper_axioms PolicyObstructions.Queue.no_restricted_policy
assert_paper_axioms PolicyObstructions.MVR.no_restricted_policy
assert_paper_axioms RGA.EmbeddingObstructions.Embedded.no_restricted_policy
assert_paper_axioms RGA.EmbeddingObstructions.Sided.no_restricted_policy
assert_paper_axioms RGA.EmbeddingObstructions.peritext_no_restricted_policy
assert_paper_axioms RGA.EmbeddingObstructions.SidedPeritext.core_no_restricted_policy
assert_paper_axioms RGA.EmbeddingObstructions.SidedPeritext.rich_no_restricted_policy
assert_paper_axioms RGA.EmbeddingObstructions.RegisteredFugueMax.no_restricted_policy
assert_paper_axioms MigrationCoverage.packages_eq_production
assert_paper_axioms MigrationCoverage.names_eq_production
assert_paper_axioms MigrationCoverage.every_production_entry
assert_paper_axioms MigrationCoverage.counts
assert_paper_axioms MigrationCoverage.exactORSet
assert_paper_axioms MigrationCoverage.efficient_direct

end Sal.MRDTs.Paper1
