import Sal.MRDTs.Metatheory.Correctness
import Sal.MRDTs.Metatheory.Safety

/-!
# Add-wins observed-remove set

This production instance stores two grow-only finite sets: tagged additions
and removed tags. An add uses its globally fresh event timestamp as its tag. A
remove carries exactly the currently live tags for one element at its issuer.
The effectors commute because the observed set is frozen in the operation.
-/

namespace Sal.MRDTs.Instances.ORSet

open Sal.MRDTs.Foundation

variable (α : Type) [DecidableEq α]

inductive OROp where
  | add (element : α)
  | remove (element : α) (observed : Finset Timestamp)
  deriving DecidableEq

abbrev AddRecord := Timestamp × α
abbrev State := Finset (AddRecord α) × Finset Timestamp

def update (state : State α) (event : Op (OROp α)) : State α :=
  match event.2.2 with
  | .add element => (insert (event.1, element) state.1, state.2)
  | .remove _ observed => (state.1, state.2 ∪ observed)

def merge (left right : State α) : State α :=
  (left.1 ∪ right.1, left.2 ∪ right.2)

def liveTags (state : State α) (element : α) : Finset Timestamp :=
  (state.1.filter fun record =>
    decide (record.2 = element ∧ record.1 ∉ state.2)).image Prod.fst

def contains (state : State α) (element : α) : Bool :=
  decide (liveTags α state element).Nonempty

def D : MRDTSig where
  State := State α
  dec_state := inferInstance
  init := (∅, ∅)
  AppOp := OROp α
  dec_op := inferInstance
  Query := α
  Value := Bool
  update := update α
  query := contains α
  merge := fun _ left right => merge α left right

variable {α}

theorem all_comm (a b : Op (OROp α)) :
    (D α).toUpdateSig.commutes a b := by
  intro state
  rcases a with ⟨atime, ar, aa⟩
  rcases b with ⟨bt, br, ba⟩
  cases aa <;> cases ba <;>
    simp only [D, update]
  all_goals
    apply Prod.ext <;>
      apply Finset.ext <;>
        intro x <;>
          simp [or_assoc, or_left_comm, or_comm]

theorem replayLaws : ReplayLaws (D α).toUpdateSig := by
  refine ⟨?_, ?_, ?_⟩
  · intro a b _ _
    constructor
    · intro h
      exact absurd (all_comm a b) h
    · rintro (h | h) <;> exact RcRes.noConfusion h
  · intro a b c _ _
    rintro ⟨h, _⟩
    exact RcRes.noConfusion h
  · intro state a b c ops _ _ _ h _
    exact RcRes.noConfusion h

theorem mergeLaws : MergeLaws (D α) := by
  refine ⟨replayLaws, ?_, ?_⟩
  · intro l a b
    apply Prod.ext <;> apply Finset.ext <;> intro x <;>
      simp [D, merge, or_comm]
  · intro state
    apply Prod.ext <;> apply Finset.ext <;> intro x <;> simp [D, merge]

theorem commutingPeelLaw : CommutingPeelLaw (D α) := by
  constructor
  · intro a event before after _ _
    apply Prod.ext <;> apply Finset.ext <;> intro x
    · rcases event with ⟨time, replica, op⟩
      cases op <;> simp [D, merge, update, or_left_comm]
    · rcases event with ⟨time, replica, op⟩
      cases op <;> simp [D, merge, update, or_left_comm, or_comm]

theorem deltaLaws : DeltaLaws (D α) := by
  constructor
  · intro m x₀ x₁ x₂ c
    apply Prod.ext <;> apply Finset.ext <;> intro x <;>
      simp [D, merge, or_left_comm]
  · intro l m x c y
    apply Prod.ext <;> apply Finset.ext <;> intro z <;>
      simp [D, merge, or_comm]

theorem join : Join (D α) :=
  JoinProof.ofArbitraryStateLaws mergeLaws deltaLaws
    (causalDeltaLaw_of_all_comm mergeLaws commutingPeelLaw all_comm)

/-- Add timestamps must be fresh in the issuer state. A remove must carry all
and only the live tags for its named element at that state. -/
def canIssue (event : Op (OROp α)) (state : State α) : Prop :=
  match event.2.2 with
  | .add _ => event.1 ∉ state.1.image Prod.fst
  | .remove element observed => observed = liveTags α state element

instance canIssueDecidable (event : Op (OROp α)) (state : State α) :
    Decidable (canIssue event state) := by
  rcases event with ⟨time, replica, op⟩
  cases op <;> simp only [canIssue] <;> infer_instance

def issuance : Issuance (D α) where
  CanIssue := canIssue

def replayAdequacy : ReplayAdequacyCertificate (D α) issuance :=
  ReplayAdequacyCertificate.ofJoin issuance join

/-! ## Ordinary-set sequential specification

The public machine deliberately forgets observed-tag payloads.  They are
implementation metadata generated by `canIssue`; an abstract remove erases
the named element from an ordinary finite set.
-/

def setStep (state : Finset α) (event : Op (OROp α)) : Finset α :=
  match event.2.2 with
  | .add element => insert element state
  | .remove element _ => state.erase element

def spec (α : Type) [DecidableEq α] : SequentialSpec (D α) where
  State := Finset α
  init := ∅
  step := setStep
  Legal := fun _ => True
  query := fun state element => decide (element ∈ state)

def stateRel (state : State α) (abstract : Finset α) : Prop :=
  ∀ element, contains α state element = decide (element ∈ abstract)

/-! The public interaction policy is semantic rather than representation
level.  Operations on different elements and same-kind operations are
independent.  A same-element add/remove pair conflicts; a concurrent remove
precedes the add, which gives the ordinary sequential explanation of add-wins.
-/

def interaction : InteractionSpec (D α) where
  interaction := fun e₁ e₂ =>
    match e₁.2.2, e₂.2.2 with
    | .add x, .remove y _ =>
        if x = y then .conflict .sndThenFst else .independent
    | .remove x _, .add y =>
        if x = y then .conflict .fstThenSnd else .independent
    | _, _ => .independent
  swap_coherent := by
    intro e₁ e₂
    rcases e₁ with ⟨t₁, r₁, o₁⟩
    rcases e₂ with ⟨t₂, r₂, o₂⟩
    cases o₁ with
    | add x =>
      cases o₂ with
      | add y => rfl
      | remove y observed =>
        by_cases h : x = y
        · subst y
          simp [Interaction.flip, ConcurrentOrder.flip]
        · have hr : y ≠ x := Ne.symm h
          simp [h, hr, Interaction.flip]
    | remove x observed =>
      cases o₂ with
      | add y =>
        by_cases h : x = y
        · subst y
          simp [Interaction.flip, ConcurrentOrder.flip]
        · have hr : y ≠ x := Ne.symm h
          simp [h, hr, Interaction.flip]
      | remove y observed' => rfl

/-! `abstractD` is the merge-free algebra of the ordinary set machine.  It is
used only to obtain the add-wins linearization order; it is not a second MRDT
implementation. -/

def abstractD (α : Type) [DecidableEq α] : UpdateSig where
  State := Finset α
  dec_state := inferInstance
  init := ∅
  AppOp := OROp α
  dec_op := inferInstance
  update := setStep

def abstractOrder (e₁ e₂ : Op (OROp α)) : RcRes :=
  match e₁.2.2, e₂.2.2 with
  | .add x, .remove y _ => if x = y then .Snd_then_fst else .Either
  | .remove x _, .add y => if x = y then .Fst_then_snd else .Either
  | _, _ => .Either

instance abstractReplayPolicy : ReplayPolicy (abstractD α) where
  order := abstractOrder

@[simp] theorem abstractD_update : (abstractD α).update = setStep := rfl

@[simp] theorem abstractD_order :
    (abstractD α).replayOrder = abstractOrder := rfl

def EqExcept (element : α) (left right : Finset α) : Prop :=
  ∀ other, other ≠ element → (other ∈ left ↔ other ∈ right)

theorem eqExcept_setStep (element : α) {left right : Finset α}
    (h : EqExcept element left right) (event : Op (OROp α)) :
    EqExcept element (setStep left event) (setStep right event) := by
  intro other hne
  rcases event with ⟨time, replica, op⟩
  cases op with
  | add added =>
      simp only [setStep, Finset.mem_insert]
      exact or_congr Iff.rfl (h other hne)
  | remove removed observed =>
      simp only [setStep, Finset.mem_erase]
      constructor
      · rintro ⟨hne', hmem⟩
        exact ⟨hne', (h other hne).mp hmem⟩
      · rintro ⟨hne', hmem⟩
        exact ⟨hne', (h other hne).mpr hmem⟩

theorem eqExcept_applySeq (element : α) {left right : Finset α}
    (h : EqExcept element left right) (ops : List (Op (OROp α))) :
    EqExcept element
      (applySeq (abstractD α) left ops)
      (applySeq (abstractD α) right ops) := by
  induction ops generalizing left right with
  | nil => exact h
  | cons event rest ih =>
      exact ih (eqExcept_setStep element h event)

theorem erase_eq_of_eqExcept (element : α) {left right : Finset α}
    (h : EqExcept element left right) :
    left.erase element = right.erase element := by
  ext other
  by_cases heq : other = element
  · subst other
    simp
  · simp [heq, h other heq]

theorem abstract_comm_add_add
    (a b : Op (OROp α)) (x y : α)
    (ha : a.2.2 = .add x) (hb : b.2.2 = .add y) :
    (abstractD α).commutes a b := by
  intro state
  simp only [abstractD_update, setStep, ha, hb]
  exact Finset.insert_comm _ _ _

theorem abstract_comm_remove_remove
    (a b : Op (OROp α)) (x y : α)
    (observed₁ observed₂ : Finset Timestamp)
    (ha : a.2.2 = .remove x observed₁)
    (hb : b.2.2 = .remove y observed₂) :
    (abstractD α).commutes a b := by
  intro state
  change Finset α at state
  simp only [abstractD_update, setStep, ha, hb]
  change (state.erase x).erase y = (state.erase y).erase x
  ext element
  simp only [Finset.mem_erase]
  tauto

theorem abstract_comm_add_remove_of_ne
    (a b : Op (OROp α)) (x y : α) (observed : Finset Timestamp)
    (ha : a.2.2 = .add x) (hb : b.2.2 = .remove y observed)
    (hne : x ≠ y) : (abstractD α).commutes a b := by
  intro state
  change Finset α at state
  simp only [abstractD_update, setStep, ha, hb]
  change (insert x state).erase y = insert x (state.erase y)
  ext element
  simp only [Finset.mem_erase, Finset.mem_insert]
  by_cases he : element = y
  · subst element
    simp [Ne.symm hne]
  · simp [he]

theorem abstract_not_comm_add_remove
    (a b : Op (OROp α)) (x : α) (observed : Finset Timestamp)
    (ha : a.2.2 = .add x) (hb : b.2.2 = .remove x observed) :
    ¬ (abstractD α).commutes a b := by
  intro h
  have h₀ := h (∅ : Finset α)
  have hx := Finset.ext_iff.mp h₀ x
  simp [abstractD_update, setStep, ha, hb] at hx

theorem abstract_not_comm_remove_add
    (a b : Op (OROp α)) (x : α) (observed : Finset Timestamp)
    (ha : a.2.2 = .remove x observed) (hb : b.2.2 = .add x) :
    ¬ (abstractD α).commutes a b :=
  fun h => abstract_not_comm_add_remove b a x observed hb ha
    (fun state => (h state).symm)

theorem abstractReplayLaws : ReplayLaws (abstractD α) := by
  refine ⟨?_, ?_, ?_⟩
  · intro e₁ e₂ _ _
    rcases h₁ : e₁.2.2 with ⟨x⟩ | ⟨x, observed₁⟩ <;>
      rcases h₂ : e₂.2.2 with ⟨y⟩ | ⟨y, observed₂⟩
    · simp only [abstractD_order, abstractOrder, h₁, h₂]
      constructor
      · intro h
        exact absurd (abstract_comm_add_add e₁ e₂ x y h₁ h₂) h
      · rintro (h | h) <;> exact RcRes.noConfusion h
    · by_cases hxy : x = y
      · subst y
        simp only [abstractD_order, abstractOrder, h₁, h₂]
        exact ⟨fun _ => Or.inr rfl,
          fun _ => abstract_not_comm_add_remove e₁ e₂ x observed₂ h₁ h₂⟩
      · have hyx : y ≠ x := Ne.symm hxy
        simp only [abstractD_order, abstractOrder, h₁, h₂,
          if_neg hxy, if_neg hyx]
        constructor
        · intro h
          exact absurd
            (abstract_comm_add_remove_of_ne e₁ e₂ x y observed₂ h₁ h₂ hxy) h
        · rintro (h | h) <;> exact RcRes.noConfusion h
    · by_cases hxy : x = y
      · subst y
        simp only [abstractD_order, abstractOrder, h₁, h₂]
        exact ⟨fun _ => Or.inl rfl,
          fun _ => abstract_not_comm_remove_add e₁ e₂ x observed₁ h₁ h₂⟩
      · have hyx : y ≠ x := Ne.symm hxy
        simp only [abstractD_order, abstractOrder, h₁, h₂,
          if_neg hxy, if_neg hyx]
        constructor
        · intro h
          have hc := abstract_comm_add_remove_of_ne
            e₂ e₁ y x observed₁ h₂ h₁ hyx
          exact absurd (fun state => (hc state).symm) h
        · rintro (h | h) <;> exact RcRes.noConfusion h
    · simp only [abstractD_order, abstractOrder, h₁, h₂]
      constructor
      · intro h
        exact absurd
          (abstract_comm_remove_remove e₁ e₂ x y observed₁ observed₂ h₁ h₂) h
      · rintro (h | h) <;> exact RcRes.noConfusion h
  · rintro e₁ e₂ e₃ _ _ ⟨h₁₂, h₂₃⟩
    rcases h₁ : e₁.2.2 with ⟨x⟩ | ⟨x, observed₁⟩ <;>
      rcases h₂ : e₂.2.2 with ⟨y⟩ | ⟨y, observed₂⟩ <;>
      rcases h₃ : e₃.2.2 with ⟨z⟩ | ⟨z, observed₃⟩ <;>
      simp_all [abstractD_order, abstractOrder]
    all_goals first
      | (split at h₁₂ <;> simp_all)
      | (split at h₂₃ <;> simp_all)
  · intro state e e' e'' ops _ _ _ horder hnoncomm
    rcases he : e.2.2 with ⟨x⟩ | ⟨x, observed⟩ <;>
      rcases he' : e'.2.2 with ⟨y⟩ | ⟨y, observed'⟩
    all_goals simp only [abstractD_order, abstractOrder, he, he'] at horder
    all_goals try split at horder
    all_goals try exact RcRes.noConfusion horder
    rename_i hxy
    subst y
    rcases he'' : e''.2.2 with ⟨z⟩ | ⟨z, observed''⟩
    · exact absurd (abstract_comm_add_add e' e'' x z he' he'') hnoncomm
    · by_cases hzx : z = x
      · subst z
        have hbase : EqExcept x
            (setStep (setStep state e') e)
            (setStep (setStep state e) e') := by
          intro other hne
          simp [setStep, he, he', hne]
        have hfold := eqExcept_applySeq x hbase ops
        have herase := erase_eq_of_eqExcept x hfold
        simpa [abstractD_update, setStep, he''] using herase
      · exact absurd
          (abstract_comm_add_remove_of_ne e' e'' x z observed'' he' he''
            (Ne.symm hzx)) hnoncomm

theorem interaction_conflicts_iff (a b : Op (OROp α)) :
    (interaction.interaction a b).Conflicts ↔
      ¬ (abstractD α).commutes a b := by
  rcases ha : a.2.2 with ⟨x⟩ | ⟨x, observed₁⟩ <;>
    rcases hb : b.2.2 with ⟨y⟩ | ⟨y, observed₂⟩
  · simp only [interaction, ha, hb, Interaction.Conflicts]
    constructor
    · exact False.elim
    · intro h
      exact absurd (abstract_comm_add_add a b x y ha hb) h
  · by_cases hxy : x = y
    · subst y
      simp only [interaction, ha, hb, Interaction.Conflicts]
      exact ⟨fun _ => abstract_not_comm_add_remove a b x observed₂ ha hb,
        fun _ => True.intro⟩
    · simp only [interaction, ha, hb, if_neg hxy, Interaction.Conflicts]
      constructor
      · exact False.elim
      · intro h
        exact absurd
          (abstract_comm_add_remove_of_ne a b x y observed₂ ha hb hxy) h
  · by_cases hxy : x = y
    · subst y
      simp only [interaction, ha, hb, Interaction.Conflicts]
      exact ⟨fun _ => abstract_not_comm_remove_add a b x observed₁ ha hb,
        fun _ => True.intro⟩
    · have hyx : y ≠ x := Ne.symm hxy
      simp only [interaction, ha, hb, if_neg hxy, Interaction.Conflicts]
      have hc := abstract_comm_add_remove_of_ne
        b a y x observed₁ hb ha hyx
      exact ⟨False.elim, fun h => absurd (fun state => (hc state).symm) h⟩
  · simp only [interaction, ha, hb, Interaction.Conflicts]
    constructor
    · exact False.elim
    · intro h
      exact absurd
        (abstract_comm_remove_remove a b x y observed₁ observed₂ ha hb) h

theorem interaction_before_iff (a b : Op (OROp α)) :
    (interaction.interaction a b).FstBeforeSnd ↔
      (abstractD α).replayOrder a b = RcRes.Fst_then_snd := by
  rcases ha : a.2.2 with ⟨x⟩ | ⟨x, observed₁⟩ <;>
    rcases hb : b.2.2 with ⟨y⟩ | ⟨y, observed₂⟩
  · simp [interaction, abstractD_order, abstractOrder, ha, hb,
      Interaction.FstBeforeSnd]
  · by_cases hxy : x = y <;>
      simp [interaction, abstractD_order, abstractOrder, ha, hb,
        Interaction.FstBeforeSnd, hxy]
  · by_cases hxy : x = y <;>
      simp [interaction, abstractD_order, abstractOrder, ha, hb,
        Interaction.FstBeforeSnd, hxy]
  · simp [interaction, abstractD_order, abstractOrder, ha, hb,
      Interaction.FstBeforeSnd]

def abstractContext
    (C : ReplayContext (D α).toUpdateSig) : ReplayContext (abstractD α) where
  L := C.L
  vis := C.vis
  timestamps_distinct := C.timestamps_distinct
  vis_total_same_replica := C.vis_total_same_replica

@[simp] theorem abstractContext_events
    (C : ReplayContext (D α).toUpdateSig) :
    (abstractContext C).events = C.events := rfl

theorem interactionLoOn_iff_abstractLoOn
    (C : ReplayContext (D α).toUpdateSig)
    (E : Set (Op (OROp α))) (a b : Op (OROp α)) :
    interactionLoOn interaction C E a b ↔
      loOn (abstractContext C) E a b := by
  unfold interactionLoOn loOn
  simp only [abstractContext]
  simp_rw [interaction_conflicts_iff, interaction_before_iff]
  exact Iff.rfl

def Adds (event : Op (OROp α)) (element : α) : Prop :=
  event.2.2 = .add element

def Removes (event : Op (OROp α)) (element : α) : Prop :=
  ∃ observed, event.2.2 = .remove element observed

abbrev abstractRun (state : Finset α) (ops : List (Op (OROp α))) : Finset α :=
  applySeq (abstractD α) state ops

abbrev setRun (ops : List (Op (OROp α))) : Finset α :=
  (spec α).run ops

theorem setRun_append_single (ops : List (Op (OROp α)))
    (event : Op (OROp α)) :
    setRun (ops ++ [event]) = setStep (setRun ops) event := by
  exact SequentialSpec.run_append_single (spec α) ops event

theorem setRun_nil : setRun ([] : List (Op (OROp α))) = ∅ := rfl

theorem set_mem_applySeq_of_no_remove {state : Finset α} {element : α}
    (hmem : element ∈ state) : ∀ ops : List (Op (OROp α)),
    (∀ event ∈ ops, ¬ Removes event element) →
    element ∈ abstractRun state ops := by
  intro ops
  induction ops generalizing state with
  | nil => exact fun _ => hmem
  | cons event rest ih =>
      intro hnone
      have hevent := hnone event (by simp)
      have hrest : ∀ e ∈ rest, ¬ Removes e element := by
        intro e he
        exact hnone e (by simp [he])
      rcases hop : event.2.2 with ⟨added⟩ | ⟨removed, observed⟩
      · have hnext := ih (state := insert added state)
          (Finset.mem_insert_of_mem hmem) hrest
        simpa [abstractRun, applySeq, abstractD_update, setStep, hop] using hnext
      · have hne : removed ≠ element := by
          intro h
          subst removed
          exact hevent ⟨observed, hop⟩
        have hnext := ih (state := state.erase removed)
          (by simp [Ne.symm hne, hmem]) hrest
        simpa [abstractRun, applySeq, abstractD_update, setStep, hop] using hnext

theorem set_mem_run_of_add_suffix
    {ops pre post : List (Op (OROp α))} {add : Op (OROp α)}
    {element : α} (hsplit : ops = pre ++ add :: post)
    (hadd : Adds add element)
    (hnone : ∀ event ∈ post, ¬ Removes event element) :
    element ∈ setRun ops := by
  have hafter : element ∈ setStep (setRun pre) add := by
    unfold Adds at hadd
    simp [setStep, hadd]
  have hsuffix := set_mem_applySeq_of_no_remove hafter post hnone
  rw [hsplit]
  simpa [setRun, spec, SequentialSpec.run, SequentialMachine.run,
    abstractRun, abstractD, applySeq, List.foldl_append] using hsuffix

theorem exists_add_suffix_of_set_mem : ∀ (ops : List (Op (OROp α)))
    (element : α), element ∈ setRun ops →
    ∃ pre add post,
      ops = pre ++ add :: post ∧
      Adds add element ∧
      ∀ event ∈ post, ¬ Removes event element := by
  intro ops
  induction ops using List.reverseRecOn with
  | nil =>
      intro element hmem
      rw [setRun_nil] at hmem
      simp at hmem
  | append_singleton ops event ih =>
      intro element hmem
      rw [setRun_append_single] at hmem
      rcases hop : event.2.2 with ⟨added⟩ | ⟨removed, observed⟩
      · by_cases heq : added = element
        · subst added
          exact ⟨ops, event, [], by simp, hop, by simp⟩
        · have hpre : element ∈ setRun ops := by
            have hm : element = added ∨ element ∈ setRun ops := by
              simpa [spec, setStep, hop] using hmem
            rcases hm with hm | hm
            · exact absurd hm (Ne.symm heq)
            · exact hm
          obtain ⟨pre, add, post, hsplit, hadd, hnone⟩ := ih element hpre
          refine ⟨pre, add, post ++ [event], ?_, hadd, ?_⟩
          · simp [hsplit, List.append_assoc]
          · intro later hlater
            rw [List.mem_append] at hlater
            rcases hlater with hlater | hlater
            · exact hnone later hlater
            · simp only [List.mem_singleton] at hlater
              subst later
              intro hremove
              obtain ⟨payload, hpayload⟩ := hremove
              rw [hop] at hpayload
              cases hpayload
      · have hne : removed ≠ element := by
          intro heq
          subst removed
          simp [spec, setStep, hop] at hmem
        have hpre : element ∈ setRun ops := by
          have hm : ¬ element = removed ∧ element ∈ setRun ops := by
            simpa [spec, setStep, hop] using hmem
          exact hm.2
        obtain ⟨pre, add, post, hsplit, hadd, hnone⟩ := ih element hpre
        refine ⟨pre, add, post ++ [event], ?_, hadd, ?_⟩
        · simp [hsplit, List.append_assoc]
        · intro later hlater
          rw [List.mem_append] at hlater
          rcases hlater with hlater | hlater
          · exact hnone later hlater
          · simp only [List.mem_singleton] at hlater
            subst later
            rintro ⟨payload, hpayload⟩
            rw [hop] at hpayload
            injection hpayload with heq
            exact hne heq

theorem set_mem_iff_surviving_add
    {C : ReplayContext (D α).toUpdateSig}
    {E : Set (Op (OROp α))} {ops : List (Op (OROp α))}
    (hperm : listPermOf ops E)
    (hresp : respects ops (interactionLoOn interaction C E))
    (element : α) :
    element ∈ setRun ops ↔
      ∃ add ∈ E, Adds add element ∧
        ¬ ∃ remove ∈ E, C.vis add remove ∧ Removes remove element := by
  constructor
  · intro hmem
    obtain ⟨pre, add, post, hsplit, hadd, hnone⟩ :=
      exists_add_suffix_of_set_mem ops element hmem
    have haddList : add ∈ ops := by rw [hsplit]; simp
    refine ⟨add, (hperm.2 add).mp haddList, hadd, ?_⟩
    rintro ⟨remove, hremoveE, hvis, hremove⟩
    have hremoveList : remove ∈ ops := (hperm.2 remove).mpr hremoveE
    rw [hsplit, List.mem_append] at hremoveList
    rcases hremoveList with hremovePre | hremoveTail
    · have hresp' : respects (pre ++ add :: post)
          (interactionLoOn interaction C E) := hsplit ▸ hresp
      have hcross := (List.pairwise_append.mp hresp').2.2
      have hnot := hcross remove hremovePre add (by simp)
      apply hnot
      exact Or.inl ⟨hvis, by
        obtain ⟨observed, hremoveOp⟩ := hremove
        unfold Adds at hadd
        simp [interaction, hadd, hremoveOp, Interaction.Conflicts]⟩
    · simp only [List.mem_cons] at hremoveTail
      rcases hremoveTail with rfl | hremovePost
      · obtain ⟨observed, hremoveOp⟩ := hremove
        unfold Adds at hadd
        rw [hadd] at hremoveOp
        cases hremoveOp
      · exact hnone remove hremovePost hremove
  · rintro ⟨add, haddE, hadd, hsurvives⟩
    have haddList : add ∈ ops := (hperm.2 add).mpr haddE
    obtain ⟨pre, post, hsplit⟩ := List.mem_iff_append.mp haddList
    apply set_mem_run_of_add_suffix hsplit hadd
    intro remove hremovePost hremove
    have hremoveList : remove ∈ ops := by rw [hsplit]; simp [hremovePost]
    have hremoveE : remove ∈ E := (hperm.2 remove).mp hremoveList
    have hresp' : respects (pre ++ add :: post)
        (interactionLoOn interaction C E) := hsplit ▸ hresp
    have htailPair := (List.pairwise_append.mp hresp').2.1
    have hnotEdge := (List.pairwise_cons.mp htailPair).1 remove hremovePost
    by_cases har : C.vis add remove
    · exact hsurvives ⟨remove, hremoveE, har, hremove⟩
    by_cases hra : C.vis remove add
    · apply hnotEdge
      exact Or.inl ⟨hra, by
        obtain ⟨observed, hremoveOp⟩ := hremove
        unfold Adds at hadd
        simp [interaction, hadd, hremoveOp, Interaction.Conflicts]⟩
    apply hnotEdge
    refine Or.inr ⟨hra, har, ?_, ?_⟩
    · obtain ⟨observed, hremoveOp⟩ := hremove
      unfold Adds at hadd
      simp [interaction, hadd, hremoveOp, Interaction.FstBeforeSnd]
    · rintro ⟨absorber, habsE, habsVis, habsConflict⟩
      apply hsurvives
      refine ⟨absorber, habsE, habsVis, ?_⟩
      rcases habsOp : absorber.2.2 with ⟨added⟩ | ⟨removed, observed⟩
      · unfold Adds at hadd
        simp [interaction, hadd, habsOp, Interaction.Conflicts] at habsConflict
      · unfold Adds at hadd
        have heq : element = removed := by
          by_contra hne
          simp [interaction, hadd, habsOp, hne,
            Interaction.Conflicts] at habsConflict
        subst removed
        exact ⟨observed, habsOp⟩

theorem add_record_mem_fold_iff (ops : List (Op (OROp α)))
    (tag : Timestamp) (element : α) :
    (tag, element) ∈
        (applySeq (D α).toUpdateSig (D α).init ops).1 ↔
      ∃ replica, (tag, replica, .add element) ∈ ops := by
  induction ops using List.reverseRecOn with
  | nil => simp [applySeq, D]
  | append_singleton ops event ih =>
      rw [applySeq_append_single]
      rcases event with ⟨time, replica, op⟩
      cases op with
      | add added =>
          rw [MRDTSig.toUpdateSig_update]
          change
            (tag, element) ∈
                (update α
                  (applySeq (D α).toUpdateSig (D α).init ops)
                  (time, replica, .add added)).1 ↔
              ∃ r, (tag, r, .add element) ∈ ops ++ [(time, replica, .add added)]
          simp only [update, Finset.mem_insert]
          rw [ih]
          simp only [List.mem_append, List.mem_singleton, Prod.mk.injEq]
          aesop
      | remove removed observed =>
          rw [MRDTSig.toUpdateSig_update]
          change
            (tag, element) ∈
                (update α
                  (applySeq (D α).toUpdateSig (D α).init ops)
                  (time, replica, .remove removed observed)).1 ↔
              ∃ r, (tag, r, .add element) ∈
                ops ++ [(time, replica, .remove removed observed)]
          simp only [update]
          rw [ih]
          simp

theorem removed_tag_mem_fold_iff (ops : List (Op (OROp α)))
    (tag : Timestamp) :
    tag ∈ (applySeq (D α).toUpdateSig (D α).init ops).2 ↔
      ∃ time replica element observed,
        (time, replica, .remove element observed) ∈ ops ∧ tag ∈ observed := by
  induction ops using List.reverseRecOn with
  | nil => simp [applySeq, D]
  | append_singleton ops event ih =>
      rw [applySeq_append_single]
      rcases event with ⟨time, replica, op⟩
      cases op with
      | add added =>
          rw [MRDTSig.toUpdateSig_update]
          change
            tag ∈
                (update α
                  (applySeq (D α).toUpdateSig (D α).init ops)
                  (time, replica, .add added)).2 ↔
              ∃ t r x observed,
                (t, r, .remove x observed) ∈
                    ops ++ [(time, replica, .add added)] ∧
                  tag ∈ observed
          simp only [update]
          rw [ih]
          simp
      | remove removed observed =>
          rw [MRDTSig.toUpdateSig_update]
          change
            tag ∈
                (update α
                  (applySeq (D α).toUpdateSig (D α).init ops)
                  (time, replica, .remove removed observed)).2 ↔
              ∃ t r x payload,
                (t, r, .remove x payload) ∈
                    ops ++ [(time, replica, .remove removed observed)] ∧
                  tag ∈ payload
          simp only [update, Finset.mem_union]
          rw [ih]
          simp only [List.mem_append, List.mem_singleton, Prod.mk.injEq]
          aesop

theorem mem_liveTags_iff (state : State α) (element : α)
    (tag : Timestamp) :
    tag ∈ liveTags α state element ↔
      (tag, element) ∈ state.1 ∧ tag ∉ state.2 := by
  simp [liveTags]

/-! Issuance is the representation invariant that makes the tag implementation
refine the ordinary-set machine.  The first lemma says that a remove cannot
invent a tag: every payload tag denotes a same-element add visible to it. -/

theorem remove_payload_sound_of_execution
    {C : Configuration (D α)}
    (exec : CertifiedExecution (D α) issuance C)
    {v : Version} {state : State α} {E : Set (Op (OROp α))}
    (hver : C.ver v = some (state, E))
    {time : Timestamp} {replica : Replica} {element : α}
    {observed : Finset Timestamp} {tag : Timestamp}
    (hremove : (time, replica, .remove element observed) ∈ E)
    (htag : tag ∈ observed) :
    ∃ addReplica,
      (tag, addReplica, .add element) ∈ E ∧
      C.vis (tag, addReplica, .add element)
        (time, replica, .remove element observed) := by
  have hgood : CanonicalConfig C :=
    exec.canonicalConfig (fun C _ => (join (α := α)).at C.replayContext)
  have hsub := hgood.version_events_supported v state E hver
  have hclosed := hgood.version_events_causal v state E hver
  have hmint : MintHonest (D α) canIssue C := exec.mintHonest
  obtain ⟨past, hpast, _, hguard⟩ := hmint _ (hsub _ hremove)
  change observed = liveTags α
    (applySeq (D α).toUpdateSig (D α).init past) element at hguard
  have hlive : tag ∈ liveTags α
      (applySeq (D α).toUpdateSig (D α).init past) element := by
    rw [← hguard]
    exact htag
  have haddRecord := (mem_liveTags_iff
    (applySeq (D α).toUpdateSig (D α).init past) element tag).mp hlive
  obtain ⟨addReplica, haddPast⟩ :=
    (add_record_mem_fold_iff past tag element).mp haddRecord.1
  have haddSet := (hpast.2 _).mp haddPast
  exact ⟨addReplica,
    hclosed _ _ haddSet.2 hremove,
    haddSet.2⟩

/-- Static consequences of honest issuance for one causally closed version. -/
structure VersionWellFormed
    (C : Configuration (D α)) (E : Set (Op (OROp α))) : Prop where
  time_unique : ∀ {a b}, a ∈ E → b ∈ E → a.1 = b.1 → a = b
  payload_sound :
    ∀ {time replica element observed tag},
      (time, replica, .remove element observed) ∈ E → tag ∈ observed →
      ∃ addReplica,
        (tag, addReplica, .add element) ∈ E ∧
        C.vis (tag, addReplica, .add element)
          (time, replica, .remove element observed)
  visible_add_killed :
    ∀ {tag addReplica element time removeReplica observed},
      (tag, addReplica, .add element) ∈ E →
      (time, removeReplica, .remove element observed) ∈ E →
      C.vis (tag, addReplica, .add element)
        (time, removeReplica, .remove element observed) →
      ∃ killTime killReplica payload,
        (killTime, killReplica, .remove element payload) ∈ E ∧
        tag ∈ payload

theorem versionWellFormed_of_execution
    {C : Configuration (D α)}
    (exec : CertifiedExecution (D α) issuance C)
    {v : Version} {state : State α} {E : Set (Op (OROp α))}
    (hver : C.ver v = some (state, E)) : VersionWellFormed C E := by
  have hgood : CanonicalConfig C :=
    exec.canonicalConfig (fun C _ => (join (α := α)).at C.replayContext)
  have hsub := hgood.version_events_supported v state E hver
  have hclosed := hgood.version_events_causal v state E hver
  have hmint : MintHonest (D α) canIssue C := exec.mintHonest
  refine ⟨?_, ?_, ?_⟩
  · intro a b ha hb htime
    exact C.replayContext.ts_unique (hsub a ha) (hsub b hb) htime
  · intro time replica element observed tag hremove htag
    exact remove_payload_sound_of_execution exec hver hremove htag
  · intro tag addReplica element time removeReplica observed hadd hremove hvis
    obtain ⟨past, hpast, _, hguard⟩ := hmint _ (hsub _ hremove)
    change observed = liveTags α
      (applySeq (D α).toUpdateSig (D α).init past) element at hguard
    have haddPast : (tag, addReplica, .add element) ∈ past :=
      (hpast.2 _).mpr ⟨hsub _ hadd, hvis⟩
    have haddRecord : (tag, element) ∈
        (applySeq (D α).toUpdateSig (D α).init past).1 :=
      (add_record_mem_fold_iff past tag element).mpr ⟨addReplica, haddPast⟩
    by_cases hremoved : tag ∈
        (applySeq (D α).toUpdateSig (D α).init past).2
    · obtain ⟨killTime, killReplica, killedElement, payload,
          hkillPast, htagPayload⟩ :=
        (removed_tag_mem_fold_iff past tag).mp hremoved
      have hkillSet := (hpast.2 _).mp hkillPast
      have hkillE := hclosed _ _ hkillSet.2 hremove
      obtain ⟨otherAddReplica, hotherAddE, _⟩ :=
        remove_payload_sound_of_execution exec hver hkillE htagPayload
      have haddEq :
          (tag, addReplica, OROp.add element) =
            (tag, otherAddReplica, OROp.add killedElement) :=
        C.replayContext.ts_unique (hsub _ hadd) (hsub _ hotherAddE) rfl
      have helement : killedElement = element := by
        have h : element = killedElement := by
          simpa using congrArg (fun event : Op (OROp α) => event.2.2) haddEq
        exact h.symm
      subst killedElement
      exact ⟨killTime, killReplica, payload, hkillE, htagPayload⟩
    · have hlive : tag ∈ liveTags α
          (applySeq (D α).toUpdateSig (D α).init past) element :=
        (mem_liveTags_iff _ element tag).mpr ⟨haddRecord, hremoved⟩
      have htagObserved : tag ∈ observed := by
        rw [hguard]
        exact hlive
      exact ⟨time, removeReplica, observed, hremove, htagObserved⟩

theorem contains_fold_true_iff_surviving_add
    {C : Configuration (D α)} {E : Set (Op (OROp α))}
    (wellFormed : VersionWellFormed C E)
    {ops : List (Op (OROp α))} (hperm : listPermOf ops E)
    (element : α) :
    contains α (applySeq (D α).toUpdateSig (D α).init ops) element = true ↔
      ∃ add ∈ E, Adds add element ∧
        ¬ ∃ remove ∈ E, C.vis add remove ∧ Removes remove element := by
  constructor
  · intro hcontains
    simp only [contains, decide_eq_true_eq] at hcontains
    obtain ⟨tag, hlive⟩ := hcontains
    have hlive' := (mem_liveTags_iff
      (applySeq (D α).toUpdateSig (D α).init ops) element tag).mp hlive
    obtain ⟨addReplica, haddOps⟩ :=
      (add_record_mem_fold_iff ops tag element).mp hlive'.1
    let add : Op (OROp α) := (tag, addReplica, .add element)
    have haddE : add ∈ E := (hperm.2 add).mp haddOps
    refine ⟨add, haddE, rfl, ?_⟩
    rintro ⟨remove, hremoveE, hvis, hremoves⟩
    rcases remove with ⟨time, removeReplica, op⟩
    obtain ⟨observed, hop⟩ := hremoves
    change op = .remove element observed at hop
    subst op
    obtain ⟨killTime, killReplica, payload, hkillE, htagPayload⟩ :=
      wellFormed.visible_add_killed haddE hremoveE hvis
    have hkillOps : (killTime, killReplica, .remove element payload) ∈ ops :=
      (hperm.2 _).mpr hkillE
    have htagRemoved : tag ∈
        (applySeq (D α).toUpdateSig (D α).init ops).2 :=
      (removed_tag_mem_fold_iff ops tag).mpr
        ⟨killTime, killReplica, element, payload, hkillOps, htagPayload⟩
    exact hlive'.2 htagRemoved
  · rintro ⟨add, haddE, hadd, hsurvives⟩
    rcases add with ⟨tag, addReplica, op⟩
    change op = .add element at hadd
    subst op
    have haddOps : (tag, addReplica, .add element) ∈ ops :=
      (hperm.2 _).mpr haddE
    have haddRecord : (tag, element) ∈
        (applySeq (D α).toUpdateSig (D α).init ops).1 :=
      (add_record_mem_fold_iff ops tag element).mpr ⟨addReplica, haddOps⟩
    have hnotRemoved : tag ∉
        (applySeq (D α).toUpdateSig (D α).init ops).2 := by
      intro hremoved
      obtain ⟨time, removeReplica, removedElement, observed,
          hremoveOps, htagObserved⟩ :=
        (removed_tag_mem_fold_iff ops tag).mp hremoved
      have hremoveE :
          (time, removeReplica, .remove removedElement observed) ∈ E :=
        (hperm.2 _).mp hremoveOps
      obtain ⟨otherAddReplica, hotherAddE, hvis⟩ :=
        wellFormed.payload_sound hremoveE htagObserved
      have haddEq :
          (tag, addReplica, OROp.add element) =
            (tag, otherAddReplica, OROp.add removedElement) :=
        wellFormed.time_unique haddE hotherAddE rfl
      have helement : removedElement = element := by
        have h : element = removedElement := by
          simpa using congrArg (fun event : Op (OROp α) => event.2.2) haddEq
        exact h.symm
      subst removedElement
      have hvis' : C.vis (tag, addReplica, .add element)
          (time, removeReplica, .remove element observed) := by
        rw [haddEq]
        exact hvis
      exact hsurvives ⟨(time, removeReplica, .remove element observed),
        hremoveE, hvis', ⟨observed, rfl⟩⟩
    simp only [contains, decide_eq_true_eq]
    exact ⟨tag, (mem_liveTags_iff _ element tag).mpr
      ⟨haddRecord, hnotRemoved⟩⟩

theorem fold_stateRel
    {C : Configuration (D α)} {E : Set (Op (OROp α))}
    (wellFormed : VersionWellFormed C E)
    {ops : List (Op (OROp α))} (hperm : listPermOf ops E)
    (hresp : respects ops
      (interactionLoOn interaction C.replayContext E)) :
    stateRel (applySeq (D α).toUpdateSig (D α).init ops) (setRun ops) := by
  intro element
  apply Bool.eq_iff_iff.mpr
  rw [contains_fold_true_iff_surviving_add wellFormed hperm element]
  simp only [decide_eq_true_eq]
  exact (set_mem_iff_surviving_add hperm hresp element).symm

/-- Every issuance-certified OR-set version has an add-wins linearization in
the ordinary finite-set machine.  `canIssue` enters exactly through
`versionWellFormed_of_execution`; without it, the refinement is false. -/
noncomputable def setSequentialCorrectness :
    SequentialCorrectnessCertificate (D α) issuance interaction
      (spec α) stateRel where
  sound := by
    intro C exec replay v state E hver
    have hgood : CanonicalConfig C :=
      exec.canonicalConfig (fun C _ => (join (α := α)).at C.replayContext)
    have hsub := hgood.version_events_supported v state E hver
    obtain ⟨base, hbasePerm, _, hbaseFold⟩ := replay v state E hver
    obtain ⟨ops, hperm, habstractResp⟩ :=
      exists_loOn_respecting_perm_of_replayLaws
        (D := abstractD α) (C := abstractContext C.replayContext)
        (abstractReplayLaws (α := α)) hgood.vis_trans hgood.vis_irrefl
        hbasePerm (fun event hevent => by simpa using hsub event hevent)
    have hresp : respects ops
        (interactionLoOn interaction C.replayContext E) := by
      unfold respects at habstractResp ⊢
      exact habstractResp.imp fun {a b} hab hba =>
        hab ((interactionLoOn_iff_abstractLoOn C.replayContext E b a).mp hba)
    have hlistPerm : ops.Perm base := by
      rw [List.perm_ext_iff_of_nodup hperm.1 hbasePerm.1]
      intro event
      exact (hperm.2 event).trans (hbasePerm.2 event).symm
    have hfold :
        applySeq (D α).toUpdateSig (D α).init ops = state :=
      (applySeq_perm_of_all_comm (D' := (D α).toUpdateSig)
        all_comm hlistPerm (D α).init).trans hbaseFold
    have wellFormed := versionWellFormed_of_execution exec hver
    have hrelFold := fold_stateRel wellFormed hperm hresp
    have hrel : stateRel state (setRun ops) := by
      simpa [hfold] using hrelFold
    refine ⟨ops, hperm, hresp, True.intro, hrel, ?_⟩
    intro query
    simpa [D, spec, setRun] using hrel query

noncomputable def verified : VerifiedMRDT (D α) where
  issuance := issuance
  interaction := interaction
  replayAdequacy := replayAdequacy
  Spec := spec α
  Rel := stateRel
  sequentialCorrectness := setSequentialCorrectness

/-! ## Issuance and add-wins SPOTs -/

def addA : Op (OROp Nat) := (1, 0, .add 7)
def removeObserved : Op (OROp Nat) := (2, 0, .remove 7 {1})
def removeConcurrent : Op (OROp Nat) := (3, 1, .remove 7 ∅)
def afterAdd : State Nat := update Nat (D Nat).init addA

theorem add_fresh_issuable : canIssue addA (D Nat).init := by native_decide

theorem observed_remove_issuable : canIssue removeObserved afterAdd := by
  native_decide

theorem omitted_observed_tag_rejected : ¬ canIssue removeConcurrent afterAdd := by
  native_decide

theorem fabricated_tag_rejected :
    ¬ canIssue (4, 0, .remove 7 {99}) afterAdd := by native_decide

theorem observed_remove_removes :
    contains Nat (update Nat afterAdd removeObserved) 7 = false := by
  native_decide

theorem concurrent_remove_add_wins :
    contains Nat
      (update Nat (update Nat (D Nat).init removeConcurrent) addA) 7 = true := by
  native_decide

theorem observed_remove_ordinary_spec_absent :
    7 ∉ setRun [addA, removeObserved] := by native_decide

theorem concurrent_remove_ordinary_spec_add_wins :
    7 ∈ setRun [removeConcurrent, addA] := by native_decide

/-- Negative control: if the omitted-tag remove were admitted after `addA`,
the tag implementation would retain `7` while the ordinary sequential set
would erase it.  This is the precise reason `canIssue` is load-bearing. -/
theorem omitted_tag_breaks_ordinary_refinement :
    contains Nat
        (applySeq (D Nat).toUpdateSig (D Nat).init [addA, removeConcurrent]) 7 =
          true ∧
      7 ∉ setRun [addA, removeConcurrent] := by
  native_decide

#print axioms verified
#print axioms observed_remove_issuable
#print axioms omitted_observed_tag_rejected
#print axioms concurrent_remove_add_wins
#print axioms omitted_tag_breaks_ordinary_refinement

end Sal.MRDTs.Instances.ORSet
