import Sal.MRDTs.Metatheory.Join.Assoc_CounterModel
import Sal.MRDTs.Metatheory.Join.RA_Lin_Of_Join

/-!
# The Join Lemma from lattice laws + update-inflationarity + the
# causal-delta bound (CD)

`Assoc_CounterModel.lean` shows `CoreVCs` + the bounded
join-semilattice laws (`LatticeVCs`) do not imply `JoinPeelVCs`: the
`AWSetF` separator has a *deflationary* update. This file mechanizes
the conditional theorem: adding

* `update_inflation`: `s ⊔ update s e = update s e`, the second half
  of the state-based-CRDT contract (`LatticeVCsPlus`), and
* the **causal-delta bound** `CDVC`: for a `loOn(U)`-maximal `e`,
  `update σ(U∖e) e ⊑ σ(U∖e) ⊔ update σ(↓e∖e) e` where `↓e` is the
  `vis∧¬commutes` past of `e` ("the effect of `e` on the full
  canonical state is generated by its effect on its own causal past,
  modulo the state itself")

yields the full Join Lemma, hence (via the bridge machinery)
end-to-end RA-linearizability:

    ra_linearizable_of_core_lattice_cd :
      CoreVCs D → LatticeVCsPlus D → CDVC D →
      ReachableFrom initConfig C → IsRALinearizable C

## The proof

Strong induction on `n = |E₁ ∪ E₂|` (measured by any enumeration).
Write `⊔` for merge and `x ⊑ y` for `x ⊔ y = y`.

* **Order algebra (free).** ACI + `merge_init` make `⊑` a partial
  order with joins; `lem_0op` alone makes `update` *monotone*
  (`update_mono`); `update_inflation` makes it inflationary.
* **Free peel of a principal downset.** Everything in `↓e∖{e}` is
  `vis`-before `e`, so `e` is automatically `loOn(↓e)`-maximal
  (`downset_max`, no VC needed) and `σ(↓e) = update σ(↓e∖e) e` by
  `isCanonicalState_snoc`.
* **The principal case `P(U,e)`** (`principal_case`): for `e`
  `loOn(U)`-maximal, `σ(U∖e) ⊔ σ(↓e) = update σ(U∖e) e (= σ(U))`.
  `⊑`: absorption `σ(↓e∖e) ⊑ σ(U∖e)` is the induction hypothesis at
  size `n−1`; monotonicity and inflation then bound both join
  components by `update σ(U∖e) e`. `⊒`: exactly `CDVC`.
  Antisymmetry closes.
* **Side decomposition** (`side_decomposition`): each side `E ∋ e`
  satisfies `σ(E) = σ(E∖e) ⊔ σ(↓e)`, by the IH at `|E| < n` when
  `E ⊊ U`, and by `P(U,e)` itself when `E = U`. This dissolves the
  *buried-event* difficulty: the decomposition never asks for a peel
  of `e` from the side's own linearization (which may not exist, as
  the associative counter-model shows), only for the join-decomposition.
* **Combine** (`join_lemma_of_cd`): with `e` in one or both sides,
  re-associate (ACI; idempotence collapses the shared `σ(↓e) ⊔ σ(↓e)`)
  and contract the `e`-free residue to `σ(U∖e)` by the IH at `n−1`;
  `P(U,e)` finishes. Notably no separate subset/absorption case is
  needed: absorption instances are exactly the `E = U` branch of the
  side decomposition.

The per-CRDT discharge of `CDVC` for `AWSet` is in
`CD_AWSet.lean`; the boundary from below is
`AWSetF_not_latticeVCsPlus` here (the `AWSetF` separator fails exactly
`update_inflation`).
-/

namespace Sal.MRDTs.Foundation

open Classical

section
variable {D : CRDTSig}

/-! ### 0. The bundles -/

/-- `LatticeVCs` plus update-inflationarity: the complete
state-based-CRDT contract (merge is a bounded semilattice join,
updates inflate). Every real state-based RDT satisfies this
definitionally. -/
structure LatticeVCsPlus (D : CRDTSig) : Prop where
  merge_assoc :
    ∀ a b c : D.State,
      D.merge (D.merge a b) c = D.merge a (D.merge b c)
  merge_idem : ∀ s : D.State, D.merge s s = s
  update_inflation :
    ∀ (s : D.State) (e : Op D.AppOp),
      D.merge s (D.update s e) = D.update s e

theorem LatticeVCsPlus.toLatticeVCs (h : LatticeVCsPlus D) :
    LatticeVCs D :=
  ⟨h.merge_assoc, h.merge_idem⟩

/-- The separator `AWSetF` fails exactly `update_inflation`: its
lattice laws hold (`AWSetF_latticeVCs`) but `rem` deflates the flag. -/
theorem AWSetF_not_latticeVCsPlus : ¬ LatticeVCsPlus AWSetF :=
  fun h => AWSetF_update_not_inflationary h.update_inflation

/-! ### 1. Order algebra: `x ⊑ y := (merge x y = y)` -/

/-- Joins of lower bounds are lower bounds. -/
private theorem merge_below (hL : LatticeVCsPlus D) {x y z : D.State}
    (hx : D.merge x z = z) (hy : D.merge y z = z) :
    D.merge (D.merge x y) z = z := by
  rw [hL.merge_assoc, hy, hx]

/-- `update` is monotone, from `lem_0op` alone. -/
private theorem update_mono (hVC : CoreVCs D) {x y : D.State}
    (h : D.merge x y = y) (e : Op D.AppOp) :
    D.merge (D.update x e) (D.update y e) = D.update y e := by
  rw [hVC.lem_0op, h]

/-- Antisymmetry of `⊑`. -/
private theorem merge_antisymm (hVC : CoreVCs D) {x y : D.State}
    (hxy : D.merge x y = y) (hyx : D.merge y x = x) : x = y := by
  rw [← hyx, hVC.merge_comm]
  exact hxy

/-- `(a ⊔ b) ⊔ c = (a ⊔ c) ⊔ b`. -/
private theorem merge_right_comm (hVC : CoreVCs D)
    (hL : LatticeVCsPlus D) (a b c : D.State) :
    D.merge (D.merge a b) c = D.merge (D.merge a c) b := by
  rw [hL.merge_assoc, hVC.merge_comm b c, ← hL.merge_assoc]

/-- `(a ⊔ b) ⊔ (c ⊔ d) = (a ⊔ c) ⊔ (b ⊔ d)`. -/
private theorem merge_merge_merge (hVC : CoreVCs D)
    (hL : LatticeVCsPlus D) (a b c d : D.State) :
    D.merge (D.merge a b) (D.merge c d)
      = D.merge (D.merge a c) (D.merge b d) := by
  rw [hL.merge_assoc a b, ← hL.merge_assoc b c d, hVC.merge_comm b c,
      hL.merge_assoc c b d, ← hL.merge_assoc a c (D.merge b d)]

/-! ### 2. Principal downsets

`downset C e` is the `vis ∧ ¬commutes` backward closure of `{e}`,
the events whose effect `e`'s issuing replica had necessarily
incorporated (up to commutation) when it performed `e`. -/

/-- One backward step: a `vis ∧ ¬commutes` edge. -/
def visNC (C : Configuration D) (a b : Op D.AppOp) : Prop :=
  C.vis a b ∧ ¬ D.commutes a b

/-- The principal downset of `e`. -/
def downset (C : Configuration D) (e : Op D.AppOp) :
    Set (Op D.AppOp) :=
  {x | x = e ∨ Relation.TransGen (visNC C) x e}

theorem self_mem_downset {C : Configuration D} {e : Op D.AppOp} :
    e ∈ downset C e :=
  Or.inl rfl

/-- The downset is contained in every backward-closed set containing
`e`. -/
theorem downset_subset {C : Configuration D} {e : Op D.AppOp}
    {W : Set (Op D.AppOp)}
    (h_cl : ∀ a b, C.vis a b → ¬ D.commutes a b → b ∈ W → a ∈ W)
    (h_e : e ∈ W) :
    downset C e ⊆ W := by
  rintro x (rfl | h)
  · exact h_e
  · induction h using Relation.TransGen.head_induction_on with
    | single h' => exact h_cl _ _ h'.1 h'.2 h_e
    | head h' _ hmem => exact h_cl _ _ h'.1 h'.2 hmem

/-- The downset is backward-closed. -/
theorem downset_closed {C : Configuration D} {e : Op D.AppOp} :
    ∀ a b, C.vis a b → ¬ D.commutes a b →
      b ∈ downset C e → a ∈ downset C e := by
  rintro a b hv hnc (rfl | h)
  · exact Or.inr (Relation.TransGen.single ⟨hv, hnc⟩)
  · exact Or.inr (Relation.TransGen.head ⟨hv, hnc⟩ h)

/-- Everything in the downset (except `e`) is `vis`-before `e`. -/
theorem downset_vis {C : Configuration D} {e : Op D.AppOp}
    (h_tr : ∀ {a b c : Op D.AppOp},
      C.vis a b → C.vis b c → C.vis a c)
    {x : Op D.AppOp} (hx : x ∈ downset C e) (hne : x ≠ e) :
    C.vis x e := by
  rcases hx with rfl | h
  · exact absurd rfl hne
  · clear hne
    induction h with
    | single h' => exact h'.1
    | tail _ h' ihv => exact h_tr ihv h'.1

/-- The punctured downset is backward-closed (an edge into it from
`e` would close a `vis`-cycle). -/
theorem downset_diff_closed {C : Configuration D} {e : Op D.AppOp}
    (h_tr : ∀ {a b c : Op D.AppOp},
      C.vis a b → C.vis b c → C.vis a c)
    (h_ir : ∀ a : Op D.AppOp, ¬ C.vis a a) :
    ∀ a b, C.vis a b → ¬ D.commutes a b →
      b ∈ downset C e \ {e} → a ∈ downset C e \ {e} := by
  rintro a b hv hnc ⟨hb, hbne⟩
  refine ⟨downset_closed a b hv hnc hb, ?_⟩
  intro ha
  have ha' : a = e := ha
  subst ha'
  exact h_ir a (h_tr hv (downset_vis h_tr hb hbne))

/-- **`e` is automatically `loOn(↓e)`-maximal**: no VC needed: an
edge out of `e` into its own past closes a `vis`-cycle (first
disjunct) or contradicts `vis x e` (rc disjunct). -/
theorem downset_max {C : Configuration D} {e : Op D.AppOp}
    (h_tr : ∀ {a b c : Op D.AppOp},
      C.vis a b → C.vis b c → C.vis a c)
    (h_ir : ∀ a : Op D.AppOp, ¬ C.vis a a) :
    ∀ x ∈ downset C e, x ≠ e → ¬ loOn C (downset C e) e x := by
  intro x hx hne
  have hvxe : C.vis x e := downset_vis h_tr hx hne
  rintro (⟨hv, _⟩ | ⟨_, hnv, _, _⟩)
  · exact h_ir e (h_tr hv hvxe)
  · exact hnv hvxe

/-! ### 3. The causal-delta bound -/

/-- **(CD), the causal-delta bound**: the single residual per-CRDT
obligation for a `loOn(U)`-maximal `e`
with `A = σ(U∖e)` and `B = σ(↓e∖e)`,

    update A e ⊑ A ⊔ update B e.

The other inequality is free from the lattice laws (`principal_case`
below), so (CD) is exactly "half a peel identity": strictly weaker in
shape than either `JoinPeelVCs` equation. For `AWSet` it reduces to
the trichotomy (`CD_AWSet.lean`); for the commuting class it holds
with equality via `merge_peel_comm` (with `B` a fold of `init`). -/
def CDVC (D : CRDTSig) : Prop :=
  ∀ (C : Configuration D) (U : Set (Op D.AppOp)) (A B : D.State)
    (e : Op D.AppOp),
    (∀ {a b c : Op D.AppOp}, C.vis a b → C.vis b c → C.vis a c) →
    (∀ a : Op D.AppOp, ¬ C.vis a a) →
    (∀ a ∈ U, a ∈ C.events) →
    (∀ a b, C.vis a b → ¬ D.commutes a b → b ∈ U → a ∈ U) →
    e ∈ U →
    (∀ x ∈ U, x ≠ e → ¬ loOn C U e x) →
    IsCanonicalState C (U \ {e}) A →
    IsCanonicalState C (downset C e \ {e}) B →
    D.merge (D.update A e) (D.merge A (D.update B e))
      = D.merge A (D.update B e)

/-! ### 4. Length bookkeeping for the measure -/

private theorem listPermOf_length_lt {α : Type} {l l' : List α}
    {ev ev' : Set α} {x : α}
    (h : listPermOf l ev) (h' : listPermOf l' ev')
    (hsub : ev ⊆ ev') (hx : x ∈ ev') (hxn : x ∉ ev) :
    l.length < l'.length := by
  have hnd : (x :: l).Nodup := by
    rw [List.nodup_cons]
    exact ⟨fun hmem => hxn ((h.2 x).mp hmem), h.1⟩
  have hsp : List.Subperm (x :: l) l' := by
    refine List.subperm_of_subset hnd ?_
    intro a ha
    rcases List.mem_cons.mp ha with rfl | ha'
    · exact (h'.2 a).mpr hx
    · exact (h'.2 a).mpr (hsub ((h.2 a).mp ha'))
  have hle := hsp.length_le
  simp only [List.length_cons] at hle
  omega

/-- A subset of an enumerable set is enumerable. -/
private theorem exists_listPermOf_subset {α : Type} {l : List α}
    {T S : Set α} (h : listPermOf l T) (hsub : S ⊆ T) :
    ∃ l', listPermOf l' S := by
  classical
  refine ⟨l.filter (fun a => decide (a ∈ S)), h.1.filter _, fun a => ?_⟩
  rw [List.mem_filter]
  constructor
  · rintro ⟨_, hd⟩
    exact of_decide_eq_true hd
  · intro ha
    exact ⟨(h.2 a).mpr (hsub ha), decide_eq_true ha⟩

/-! ### 5. The master induction -/

/-- The Join Lemma at a fixed configuration, for instances whose
union has an enumeration of length `n`. -/
private def JoinAt (C : Configuration D) (n : ℕ) : Prop :=
  ∀ (ev₁ ev₂ : Set (Op D.AppOp)) (s₁ s₂ : D.State)
    (lU : List (Op D.AppOp)),
    listPermOf lU (ev₁ ∪ ev₂) → lU.length = n →
    (∀ a ∈ ev₁, a ∈ C.events) → (∀ a ∈ ev₂, a ∈ C.events) →
    (∀ a b, C.vis a b → ¬ D.commutes a b → b ∈ ev₁ → a ∈ ev₁) →
    (∀ a b, C.vis a b → ¬ D.commutes a b → b ∈ ev₂ → a ∈ ev₂) →
    IsCanonicalState C ev₁ s₁ → IsCanonicalState C ev₂ s₂ →
    IsCanonicalState C (ev₁ ∪ ev₂) (D.merge s₁ s₂)

/-- **The principal case `P(U, e)`**: `σ(U∖e) ⊔ update σ(↓e∖e) e`
is `update σ(U∖e) e`, and is canonical for `U`. Consumes the IH only
through the absorption instance `(↓e∖e, U∖e)` at size `n − 1`. -/
private theorem principal_case (hVC : CoreVCs D)
    (hL : LatticeVCsPlus D) (hCD : CDVC D) {C : Configuration D}
    (h_tr : ∀ {a b c : Op D.AppOp},
      C.vis a b → C.vis b c → C.vis a c)
    (h_ir : ∀ a : Op D.AppOp, ¬ C.vis a a)
    {n : ℕ} (IH : ∀ m, m < n → JoinAt C m)
    {U : Set (Op D.AppOp)} {lU : List (Op D.AppOp)}
    (hpU : listPermOf lU U) (hlen : lU.length = n)
    (h_in : ∀ a ∈ U, a ∈ C.events)
    (h_cl : ∀ a b, C.vis a b → ¬ D.commutes a b → b ∈ U → a ∈ U)
    {e : Op D.AppOp} (h_e : e ∈ U)
    (h_max : ∀ x ∈ U, x ≠ e → ¬ loOn C U e x)
    {A B : D.State}
    (hA : IsCanonicalState C (U \ {e}) A)
    (hB : IsCanonicalState C (downset C e \ {e}) B) :
    D.merge A (D.update B e) = D.update A e ∧
    IsCanonicalState C U (D.merge A (D.update B e)) := by
  classical
  -- Enumeration of U ∖ {e}.
  have h_e_lU : e ∈ lU := (hpU.2 e).mpr h_e
  have hpU' : listPermOf (lU.filter (· ≠ e)) (U \ {e}) :=
    filter_ne_listPermOf hpU h_e_lU
  have hlen' : (lU.filter (· ≠ e)).length = n - 1 := by
    rw [listPermOf_diff_length hpU h_e_lU hpU', hlen]
  have h_pos : 0 < n := by
    rw [← hlen]
    exact List.length_pos_of_mem h_e_lU
  -- Downset plumbing.
  have h_dsub : downset C e ⊆ U := downset_subset h_cl h_e
  have h_dsub' : downset C e \ {e} ⊆ U \ {e} :=
    fun x hx => ⟨h_dsub hx.1, hx.2⟩
  -- B ⊑ A: the absorption instance (↓e∖e, U∖e) at size n − 1.
  have hset : (downset C e \ {e}) ∪ (U \ {e}) = U \ {e} :=
    Set.ext fun x =>
      ⟨fun h => h.elim (fun hx => h_dsub' hx) id, Or.inr⟩
  have h_mBA : IsCanonicalState C ((downset C e \ {e}) ∪ (U \ {e}))
      (D.merge B A) := by
    refine IH (n - 1) (by omega) _ _ B A (lU.filter (· ≠ e)) ?_ hlen'
      (fun a ha => h_in a (h_dsub ha.1))
      (fun a ha => h_in a ha.1)
      (downset_diff_closed h_tr h_ir)
      (closure_diff_of_max Set.Subset.rfl h_cl h_max)
      hB hA
    rw [hset]
    exact hpU'
  have h_mBA' : IsCanonicalState C (U \ {e}) (D.merge B A) := by
    rw [← hset]
    exact h_mBA
  have h_below_BA : D.merge B A = A :=
    isCanonicalState_unique hVC (fun a ha => h_in a ha.1) h_mBA' hA
  -- The ⊑ chain: A ⊔ update B e ⊑ update A e.
  have h_left : D.merge (D.merge A (D.update B e)) (D.update A e)
      = D.update A e :=
    merge_below hL (hL.update_inflation A e)
      (update_mono hVC h_below_BA e)
  -- The ⊒ direction is exactly (CD).
  have h_right : D.merge (D.update A e) (D.merge A (D.update B e))
      = D.merge A (D.update B e) :=
    hCD C U A B e h_tr h_ir h_in h_cl h_e h_max hA hB
  have h_eq : D.merge A (D.update B e) = D.update A e :=
    merge_antisymm hVC h_left h_right
  refine ⟨h_eq, ?_⟩
  rw [h_eq]
  exact isCanonicalState_snoc h_e h_max hA

/-- **Side decomposition**: a backward-closed `E ∋ e` inside `U`
satisfies `σ(E) = σ(E∖e) ⊔ update σ(↓e∖e) e`, by the IH when
`E ⊊ U`, by `P(U,e)` when `E = U`. This is where the buried-event
case dissolves: no peel of `e` from `E`'s own linearization is ever
required. -/
private theorem side_decomposition (hVC : CoreVCs D)
    (hL : LatticeVCsPlus D) (hCD : CDVC D) {C : Configuration D}
    (h_tr : ∀ {a b c : Op D.AppOp},
      C.vis a b → C.vis b c → C.vis a c)
    (h_ir : ∀ a : Op D.AppOp, ¬ C.vis a a)
    {n : ℕ} (IH : ∀ m, m < n → JoinAt C m)
    {U : Set (Op D.AppOp)} {lU : List (Op D.AppOp)}
    (hpU : listPermOf lU U) (hlen : lU.length = n)
    (h_inU : ∀ a ∈ U, a ∈ C.events)
    (h_clU : ∀ a b, C.vis a b → ¬ D.commutes a b → b ∈ U → a ∈ U)
    {e : Op D.AppOp} (h_e : e ∈ U)
    (h_max : ∀ x ∈ U, x ≠ e → ¬ loOn C U e x)
    {A B : D.State}
    (hA : IsCanonicalState C (U \ {e}) A)
    (hB : IsCanonicalState C (downset C e \ {e}) B)
    {E : Set (Op D.AppOp)} {s t : D.State}
    (h_subE : E ⊆ U)
    (h_inE : ∀ a ∈ E, a ∈ C.events)
    (h_clE : ∀ a b, C.vis a b → ¬ D.commutes a b → b ∈ E → a ∈ E)
    (h_eE : e ∈ E)
    (hs : IsCanonicalState C E s)
    (ht : IsCanonicalState C (E \ {e}) t) :
    s = D.merge t (D.update B e) := by
  classical
  -- update B e is canonical for the downset (free peel).
  have hT : IsCanonicalState C (downset C e) (D.update B e) :=
    isCanonicalState_snoc self_mem_downset (downset_max h_tr h_ir) hB
  by_cases hEU : E = U
  · -- E = U: the principal case.
    subst hEU
    obtain ⟨h_eq, _⟩ := principal_case hVC hL hCD h_tr h_ir IH hpU hlen
      h_inU h_clU h_e h_max hA hB
    have htA : t = A :=
      isCanonicalState_unique hVC (fun a ha => h_inU a ha.1) ht hA
    have hsA : s = D.update A e :=
      isCanonicalState_unique hVC h_inU hs
        (isCanonicalState_snoc h_e h_max hA)
    rw [htA, h_eq]
    exact hsA
  · -- E ⊊ U: the IH at |E| < n.
    obtain ⟨lE, hpE, hrE, hfE⟩ := id hs
    obtain ⟨x, hxU, hxE⟩ : ∃ x ∈ U, x ∉ E := by
      by_contra h
      push_neg at h
      exact hEU (Set.Subset.antisymm h_subE h)
    have hlt : lE.length < n := by
      rw [← hlen]
      exact listPermOf_length_lt hpE hpU h_subE hxU hxE
    have h_dsubE : downset C e ⊆ E := downset_subset h_clE h_eE
    have hsetE : (E \ {e}) ∪ downset C e = E := by
      ext y
      constructor
      · rintro (hy | hy)
        · exact hy.1
        · exact h_dsubE hy
      · intro hy
        by_cases hye : y = e
        · subst hye
          exact Or.inr self_mem_downset
        · exact Or.inl ⟨hy, hye⟩
    have h_merge_can : IsCanonicalState C ((E \ {e}) ∪ downset C e)
        (D.merge t (D.update B e)) := by
      refine IH lE.length hlt _ _ t (D.update B e) lE ?_ rfl
        (fun a ha => h_inE a ha.1)
        (fun a ha => h_inE a (h_dsubE ha))
        (closure_diff_of_max h_subE h_clE h_max)
        downset_closed ht hT
      rw [hsetE]
      exact hpE
    have h_merge_can' : IsCanonicalState C E
        (D.merge t (D.update B e)) := by
      rw [← hsetE]
      exact h_merge_can
    exact isCanonicalState_unique hVC h_inE hs h_merge_can'

/-- **The Join Lemma from `CoreVCs` + lattice laws + inflation +
(CD).** Compare `join_lemma_of_peel`, which consumes the two full
peel *equations* (`JoinPeelVCs`); here the per-CRDT content is the
single *inequality* `CDVC`. -/
theorem join_lemma_of_cd (hVC : CoreVCs D) (hL : LatticeVCsPlus D)
    (hCD : CDVC D) : JoinLemma D := by
  intro C ev₁ ev₂ s₁ s₂ h_tr h_ir h_in₁ h_in₂ h_cl₁ h_cl₂ hc₁ hc₂
  classical
  obtain ⟨l₁, hp₁, hr₁, hf₁⟩ := id hc₁
  obtain ⟨l₂, hp₂, hr₂, hf₂⟩ := id hc₂
  have hpU₀ := listPermOf_union (D := D) hp₁ hp₂
  suffices gen : ∀ n, JoinAt C n by
    exact gen _ ev₁ ev₂ s₁ s₂ _ hpU₀ rfl h_in₁ h_in₂ h_cl₁ h_cl₂
      hc₁ hc₂
  intro n
  induction n using Nat.strong_induction_on with
  | _ n IH =>
    intro ev₁ ev₂ s₁ s₂ lU hpU hlen h_in₁ h_in₂ h_cl₁ h_cl₂ hc₁ hc₂
    -- Empty sides collapse via merge_init.
    rcases Set.eq_empty_or_nonempty ev₁ with h_e₁ | h_ne₁
    · have hs₁ : s₁ = D.init := isCanonicalState_empty h_e₁ hc₁
      subst h_e₁
      rw [hs₁, hVC.merge_init, Set.empty_union]
      exact hc₂
    rcases Set.eq_empty_or_nonempty ev₂ with h_e₂ | h_ne₂
    · have hs₂ : s₂ = D.init := isCanonicalState_empty h_e₂ hc₂
      subst h_e₂
      rw [hs₂, hVC.merge_comm, hVC.merge_init, Set.union_empty]
      exact hc₁
    -- Select a loOn(∪)-maximal event.
    have h_inU : ∀ a ∈ ev₁ ∪ ev₂, a ∈ C.events := by
      rintro a (h | h)
      · exact h_in₁ a h
      · exact h_in₂ a h
    have h_clU : ∀ a b, C.vis a b → ¬ D.commutes a b →
        b ∈ ev₁ ∪ ev₂ → a ∈ ev₁ ∪ ev₂ := by
      rintro a b hv hnc (h | h)
      · exact Or.inl (h_cl₁ a b hv hnc h)
      · exact Or.inr (h_cl₂ a b hv hnc h)
    obtain ⟨x₁, hx₁⟩ := h_ne₁
    obtain ⟨e, he_U, h_max⟩ :=
      exists_loOn_maximal hVC h_tr h_ir hpU h_inU ⟨x₁, Or.inl hx₁⟩
    -- σ(U∖e) and σ(↓e∖e).
    have h_e_lU : e ∈ lU := (hpU.2 e).mpr he_U
    have hpU' : listPermOf (lU.filter (· ≠ e)) ((ev₁ ∪ ev₂) \ {e}) :=
      filter_ne_listPermOf hpU h_e_lU
    have hlen' : (lU.filter (· ≠ e)).length = n - 1 := by
      rw [listPermOf_diff_length hpU h_e_lU hpU', hlen]
    have h_pos : 0 < n := by
      rw [← hlen]
      exact List.length_pos_of_mem h_e_lU
    obtain ⟨A, hA⟩ : ∃ A, IsCanonicalState C ((ev₁ ∪ ev₂) \ {e}) A :=
      isCanonicalState_exists hVC h_tr h_ir hpU'
        (fun a ha => h_inU a ha.1)
    have h_dsub : downset C e ⊆ ev₁ ∪ ev₂ := downset_subset h_clU he_U
    obtain ⟨lB, hpB⟩ :=
      exists_listPermOf_subset hpU
        (fun x (hx : x ∈ downset C e \ {e}) => h_dsub hx.1)
    obtain ⟨B, hB⟩ : ∃ B, IsCanonicalState C (downset C e \ {e}) B :=
      isCanonicalState_exists hVC h_tr h_ir hpB
        (fun a ha => h_inU a (h_dsub ha.1))
    obtain ⟨-, hP⟩ := principal_case hVC hL hCD h_tr h_ir IH hpU hlen
      h_inU h_clU he_U h_max hA hB
    -- Decompose the sides containing e and combine.
    by_cases he₁ : e ∈ ev₁
    · obtain ⟨t₁, ht₁⟩ : ∃ t, IsCanonicalState C (ev₁ \ {e}) t := by
        obtain ⟨l₁, hp₁, -, -⟩ := id hc₁
        have h_e_l₁ : e ∈ l₁ := (hp₁.2 e).mpr he₁
        exact isCanonicalState_exists hVC h_tr h_ir
          (filter_ne_listPermOf hp₁ h_e_l₁) (fun a ha => h_in₁ a ha.1)
      have hs₁ : s₁ = D.merge t₁ (D.update B e) :=
        side_decomposition hVC hL hCD h_tr h_ir IH hpU hlen h_inU
          h_clU he_U h_max hA hB Set.subset_union_left h_in₁ h_cl₁
          he₁ hc₁ ht₁
      by_cases he₂ : e ∈ ev₂
      · -- e shared: idempotence collapses the two downset copies.
        obtain ⟨t₂, ht₂⟩ : ∃ t, IsCanonicalState C (ev₂ \ {e}) t := by
          obtain ⟨l₂, hp₂, -, -⟩ := id hc₂
          have h_e_l₂ : e ∈ l₂ := (hp₂.2 e).mpr he₂
          exact isCanonicalState_exists hVC h_tr h_ir
            (filter_ne_listPermOf hp₂ h_e_l₂)
            (fun a ha => h_in₂ a ha.1)
        have hs₂ : s₂ = D.merge t₂ (D.update B e) :=
          side_decomposition hVC hL hCD h_tr h_ir IH hpU hlen h_inU
            h_clU he_U h_max hA hB Set.subset_union_right h_in₂ h_cl₂
            he₂ hc₂ ht₂
        have hsetm : (ev₁ \ {e}) ∪ (ev₂ \ {e}) = (ev₁ ∪ ev₂) \ {e} := by
          ext x
          simp only [Set.mem_union, Set.mem_diff, Set.mem_singleton_iff]
          tauto
        have h_mid_can : IsCanonicalState C ((ev₁ \ {e}) ∪ (ev₂ \ {e}))
            (D.merge t₁ t₂) := by
          refine IH (n - 1) (by omega) _ _ t₁ t₂
            (lU.filter (· ≠ e)) ?_ hlen'
            (fun a ha => h_in₁ a ha.1) (fun a ha => h_in₂ a ha.1)
            (closure_diff_of_max Set.subset_union_left h_cl₁ h_max)
            (closure_diff_of_max Set.subset_union_right h_cl₂ h_max)
            ht₁ ht₂
          rw [hsetm]
          exact hpU'
        have h_mid_can' : IsCanonicalState C ((ev₁ ∪ ev₂) \ {e})
            (D.merge t₁ t₂) := by
          rw [← hsetm]
          exact h_mid_can
        have h_mid : D.merge t₁ t₂ = A :=
          isCanonicalState_unique hVC (fun a ha => h_inU a ha.1)
            h_mid_can' hA
        rw [hs₁, hs₂, merge_merge_merge hVC hL, hL.merge_idem, h_mid]
        exact hP
      · -- e local to side 1.
        have hset₁ : (ev₁ \ {e}) ∪ ev₂ = (ev₁ ∪ ev₂) \ {e} := by
          ext x
          simp only [Set.mem_union, Set.mem_diff, Set.mem_singleton_iff]
          constructor
          · rintro (⟨h, hne⟩ | h)
            · exact ⟨Or.inl h, hne⟩
            · exact ⟨Or.inr h, fun heq => he₂ (heq ▸ h)⟩
          · rintro ⟨h | h, hne⟩
            · exact Or.inl ⟨h, hne⟩
            · exact Or.inr h
        have h_mid_can : IsCanonicalState C ((ev₁ \ {e}) ∪ ev₂)
            (D.merge t₁ s₂) := by
          refine IH (n - 1) (by omega) _ _ t₁ s₂
            (lU.filter (· ≠ e)) ?_ hlen'
            (fun a ha => h_in₁ a ha.1) h_in₂
            (closure_diff_of_max Set.subset_union_left h_cl₁ h_max)
            h_cl₂ ht₁ hc₂
          rw [hset₁]
          exact hpU'
        have h_mid_can' : IsCanonicalState C ((ev₁ ∪ ev₂) \ {e})
            (D.merge t₁ s₂) := by
          rw [← hset₁]
          exact h_mid_can
        have h_mid : D.merge t₁ s₂ = A :=
          isCanonicalState_unique hVC (fun a ha => h_inU a ha.1)
            h_mid_can' hA
        rw [hs₁, merge_right_comm hVC hL, h_mid]
        exact hP
    · -- e local to side 2.
      have he₂ : e ∈ ev₂ := by
        rcases he_U with h | h
        · exact absurd h he₁
        · exact h
      obtain ⟨t₂, ht₂⟩ : ∃ t, IsCanonicalState C (ev₂ \ {e}) t := by
        obtain ⟨l₂, hp₂, -, -⟩ := id hc₂
        have h_e_l₂ : e ∈ l₂ := (hp₂.2 e).mpr he₂
        exact isCanonicalState_exists hVC h_tr h_ir
          (filter_ne_listPermOf hp₂ h_e_l₂)
          (fun a ha => h_in₂ a ha.1)
      have hs₂ : s₂ = D.merge t₂ (D.update B e) :=
        side_decomposition hVC hL hCD h_tr h_ir IH hpU hlen h_inU
          h_clU he_U h_max hA hB Set.subset_union_right h_in₂ h_cl₂
          he₂ hc₂ ht₂
      have hset₂ : ev₁ ∪ (ev₂ \ {e}) = (ev₁ ∪ ev₂) \ {e} := by
        ext x
        simp only [Set.mem_union, Set.mem_diff, Set.mem_singleton_iff]
        constructor
        · rintro (h | ⟨h, hne⟩)
          · exact ⟨Or.inl h, fun heq => he₁ (heq ▸ h)⟩
          · exact ⟨Or.inr h, hne⟩
        · rintro ⟨h | h, hne⟩
          · exact Or.inl h
          · exact Or.inr ⟨h, hne⟩
      have h_mid_can : IsCanonicalState C (ev₁ ∪ (ev₂ \ {e}))
          (D.merge s₁ t₂) := by
        refine IH (n - 1) (by omega) _ _ s₁ t₂
          (lU.filter (· ≠ e)) ?_ hlen'
          h_in₁ (fun a ha => h_in₂ a ha.1) h_cl₁
          (closure_diff_of_max Set.subset_union_right h_cl₂ h_max)
          hc₁ ht₂
        rw [hset₂]
        exact hpU'
      have h_mid_can' : IsCanonicalState C ((ev₁ ∪ ev₂) \ {e})
          (D.merge s₁ t₂) := by
        rw [← hset₂]
        exact h_mid_can
      have h_mid : D.merge s₁ t₂ = A :=
        isCanonicalState_unique hVC (fun a ha => h_inU a ha.1)
          h_mid_can' hA
      rw [hs₂, ← hL.merge_assoc, h_mid]
      exact hP

/-! ### 6. The commuting class discharges (CD) for free

For an all-commuting `D` (G-Set and relatives), `↓e = {e}`, the
`vis∧¬commutes` past is empty, so `B = σ(∅) = init`, and the bound
holds with *equality* by `merge_peel_comm` + idempotence. Together
with `CD_AWSet.lean` this covers both classes for which `JoinPeelVCs`
had been discharged, at a fraction of the proof surface. -/

theorem cdVC_of_all_comm (hVC : CoreVCs D)
    (h_idem : ∀ s : D.State, D.merge s s = s)
    (h_comm : ∀ a b : Op D.AppOp, D.commutes a b) : CDVC D := by
  intro C U A B e _ _ _ _ _ _ hA hB
  -- The punctured downset is empty, so B = init.
  have h_down : downset C e \ {e} = ∅ := by
    ext x
    simp only [Set.mem_diff, Set.mem_singleton_iff,
      Set.mem_empty_iff_false, iff_false, not_and]
    rintro (hx | hx)
    · exact fun hne => hne hx
    · intro _
      exfalso
      cases hx with
      | single h' => exact h'.2 (h_comm _ _)
      | tail _ h' => exact h'.2 (h_comm _ _)
  have hBinit : B = D.init := isCanonicalState_empty h_down hB
  subst hBinit
  -- A ⊔ update init e = update A e, by the all-commuting peel.
  obtain ⟨ρ, hpA, _, hfA⟩ := hA
  have h_upd : D.merge A (D.update D.init e) = D.update A e := by
    rw [← hfA, hVC.merge_comm,
      hVC.merge_peel_comm D.init e ρ (fun x _ => h_comm e x),
      hVC.merge_init]
  rw [h_upd]
  exact h_idem _

/-! ### 7. End-to-end RA-linearizability

`ra_linearizable_of_core_join` consumes `JoinPeelVCs` only through
`join_lemma_of_peel`; replaying its induction with `join_lemma_of_cd`
gives the CD-form bridge. (A direct `JoinLemma → JoinPeelVCs`
implication is *not* available: the peel bundle quantifies over
configurations without `vis`-transitivity hypotheses, which the Join
Lemma needs.) -/

/-- **The bridge, CD form**: `CoreVCs` + the full state-based-CRDT
lattice contract + the causal-delta bound imply RA-linearizability of
every reachable configuration. -/
theorem ra_linearizable_of_core_lattice_cd
    (hVC : CoreVCs D) (hLat : LatticeVCsPlus D) (hCD : CDVC D)
    (C : Configuration D)
    (hReach : (labeledTS D).ReachableFrom (initConfig D) C) :
    IsRALinearizable C := by
  have hJoin : JoinLemma D := join_lemma_of_cd hVC hLat hCD
  suffices h : GoodConfig C from isRALinearizable_of_canonical h.1
  induction hReach with
  | refl => exact goodConfig_init
  | tail _ hs ih =>
    obtain ⟨ℓ, hstep⟩ := hs
    cases hstep with
    | createReplica _ _ hN hLr hvis =>
      exact goodConfig_createReplica hN hLr hvis ih
    | apply h_s h_ev h_fresh_t _ hN hLr hvis =>
      exact goodConfig_apply h_s h_ev h_fresh_t hN hLr hvis ih
    | merge h_s₁ h_s₂ h_ev₁ h_ev₂ _ hN hLr hvis =>
      exact goodConfig_merge hJoin h_s₁ h_s₂ h_ev₁ h_ev₂ hN hLr hvis ih
    | query _ _ => exact ih

end

end Sal.MRDTs.Foundation
