import Sal.ConditionedMRDTs.MRDT_Instances.VerifiedCertificates
import Sal.ConditionedMRDTs.MRDT_Instances.ProductionGenerationContracts
import Sal.ConditionedMRDTs.MRDT_Instances.FlatUnifiedCertificates
import Sal.ConditionedMRDTs.MRDT_Instances.RGA_WithTombstones.RGA_Intent
import Sal.ConditionedMRDTs.MRDT_Instances.MVR.MVR_Unified
import Sal.ConditionedMRDTs.MRDT_Instances.Peritext_WithTombstones.Peritext_Intent
import Sal.ConditionedMRDTs.MRDT_Instances.DistributedUnifiedCertificates
import Sal.ConditionedMRDTs.Metatheory.ConditioningIntentAudit
import Sal.ConditionedMRDTs.MRDT_Instances.ConsolidatedConditioningCanaries
import Sal.ConditionedMRDTs.MRDT_Instances.Peritext_Embed.PeritextFlagship
import Sal.ConditionedMRDTs.MRDT_Instances.Peritext_Sided.PeritextSided_Core
import Sal.ConditionedMRDTs.MRDT_Instances.Peritext_Sided.PeritextSided_SeqSpec
import Sal.ConditionedMRDTs.MRDT_Instances.Peritext_Sided.PeritextSided_Flagship
import Sal.ConditionedMRDTs.MRDT_Instances.Peritext_Sided.PeritextSided_Final
import Sal.ConditionedMRDTs.MRDT_Instances.Peritext_Sided.PeritextSided_Interaction
import Sal.ConditionedMRDTs.Metatheory.UnifiedVerifiedMRDT
import Sal.ConditionedMRDTs.Metatheory.Distributed_GC_Refinement
import Sal.ConditionedMRDTs.Metatheory.Distributed_GC_Acknowledgements
import Sal.ConditionedMRDTs.Metatheory.RefactorLedger

/-! Mechanically checked ledger for production `VerifiedMRDT` packages.

It also imports `RefactorLedger`; Shesha's formerly colliding update callback
is now named `sheshaUpdate`, so the production and refactor surfaces coexist in
one Lean environment.
-/

open Sal.ConditionedMRDTs

#check SequentialSpec.run_prod
#check SequentialRefinement.toHistory
#check HistorySequentialRefinement.prod
#check embedVerified
#check embedVerifiedRuntime
#check embedVerifiedRuntime_multiEpoch
#check sidedVerified
#check queueVerified
#check embedQueueVerified
#check VerifiedMRDT.ra_linearizable
#check VerifiedMRDT.sequential
#check VerifiedMRDT.prod
#check VerifiedRuntimeMRDT.compact_continuation

/-! Conditioning is classified by the public generation contract, not by the
legacy signature field.  These checks are a compile-time ledger: removing a
real issuer guard or its guard-to-history bridge breaks this module. -/
#check boundedCounterGeneration.Guard
#check boundedCounterGeneration.history_of_mint
#check bcGenHonest_of_mintHonest
#check boundedCounterSequentialRefinement
#check boundedCounterVerified
#check boundedCounterSafety
#check boundedCounterUnified
#check bcApplicable_inv_pres
#check bc_version_inv
#check bc_version_invV
#check bc_value_nonneg
#check queueGeneration.Guard
#check queueGeneration.history_of_mint
#check qHonest_of_applicable
#check embedGeneration
#check eHonest_of_applicable
#check sidedGeneration
#check sHonest_of_applicable
#check MintCertifiedReach3
#check MintCertifiedReach3V
#check honestReach_of_mintCertified
#check UnifiedVerifiedMRDT.ra_linearizable
#check UnifiedVerifiedMRDT.ra_linearizableV
#check UnifiedVerifiedMRDT.safe
#check UnifiedVerifiedMRDT.safeV
#check UnifiedVerifiedMRDT.observable
#check UnifiedVerifiedMRDT.prod
#check boundedCounter_flagship
#check boundedCounter_guarded_flagship
#check boundedCounterCertificate
#check queueUnified
#check embedUnified
#check sidedUnified
#check peritextEmbedUnified
#check counterUnified
#check iocUnified
#check pnUnified
#check orsetUnified
#check orseteUnified
#check gosetUnified
#check gomapUnified
#check lwwUnified
#check fwwUnified
#check awpqUnified
#check VerifiedMRDTF
#check UnifiedVerifiedMRDTF.ra_linearizable
#check UnifiedVerifiedMRDTF.ra_linearizableV
#check ewflagUnifiedF
#check rgaApplicable
#check RGAHistoryOK
#check rgaSequentialSound
#check rgaHistorySequentialRefinement
#check rgaGeneration
#check rgaUnified
#check mvrApplicable
#check MVRMintHistory
#check mvrGeneration
#check mvrUnified
#check ptApplicable
#check PtHistoryOK
#check ptSequentialSound
#check ptHistorySequentialRefinement
#check ptGeneration
#check ptUnified
#check DerivedEvidence
#check distributed_execution_refines_noGC
#check ValidFetchReceipt
#check acknowledge_erases
#check acknowledgedStep_refines_noGC
#check acknowledged_execution_refines_noGC
#check pruneEvidence_of_receipts
#check no_pruneEvidence_without_authored_or_receipt
#check coordinated_collect_projects_global
#check distributedConfig_refines_Step3
#check query_unavailable_without_head
#check mintCertifiedReach_of_distributed
#check UnifiedVerifiedMRDT.distributed
#check boundedCounterDistributed
#check queueDistributed
#check tombstoneRGADistributed
#check mvrDistributed
#check orsetDistributed
#check peritextTombstoneDistributed
#check peritextEmbedDistributed
#check applicable_mints_do_not_imply_eSeqOK
#check AlgebraVerifiedMRDT
#check OperationalConditioning
#check AlgebraVerifiedMRDT.ofVerified
#check AlgebraVerifiedMRDT.toVerified
#check eSeqOK_of_linearMintHistory
#check sSeqOK_of_linearMintHistory
#check embedSequentialSound_of_linearMintHistory
#check sidedSequentialSound_of_linearMintHistory
#check GenerationVerifiedMRDT.toUnified
#check GenerationVerifiedMRDT.distributedRA
#check GenerationVerifiedMRDT.distributedRAV
#check GenerationVerifiedMRDT.distributedSafe
#check GenerationVerifiedMRDT.sequential
#check embedGenerationVerified
#check sidedGenerationVerified
#check peritextEmbedGenerationVerified
#check peritextEmbedRenderedSequential_of_linearMintHistory
#check qOK_of_linearMintHistory
#check queueGenerationVerified
#check BCSequentialHonest_of_linearMintHistory
#check boundedCounterGenerationVerified
#check PeritextFlagshipCertificate
#check peritextFlagship
#check PeritextSided.Core
#check PeritextSided.CoreHonest
#check PeritextSided.core_join_at
#check PeritextSided.coreGuard
#check PeritextSided.mintHonest_text
#check PeritextSided.coreGeneration
#check PeritextSided.linearMintHistory_text
#check PeritextSided.textSequentialSound
#check PeritextSided.richSequentialSpec
#check PeritextSided.richStateRel
#check PeritextSided.richSequentialSound
#check PeritextSided.coreVerified
#check PeritextSided.preGCUnified
#check PeritextSided.distributedPreGC
#check PeritextSided.localRichIntent
#check PeritextSided.StateGC.naive_three_component_gc_is_not_continuation_safe
#check PeritextSided.StateGC.CompactSidedState
#check PeritextSided.StateGC.CompactState
#check PeritextSided.StateGC.Plan.WellFormed
#check PeritextSided.StateGC.gapEntryOf_exact
#check PeritextSided.StateGC.compactInsertOp_exact
#check PeritextSided.StateGC.compactInsertOp_applicable
#check PeritextSided.StateGC.compactGapMerge_exact
#check PeritextSided.StateGC.collectText_render_preserved
#check PeritextSided.StateGC.applySeq_s_filter
#check PeritextSided.StateGC.collectedText_continuation_render
#check PeritextSided.StateGC.trimDeleted_render_preserved
#check PeritextSided.StateGC.dropMarkPair_render_preserved
#check PeritextSided.StateGC.AtomicBaseCertificate
#check PeritextSided.StateGC.FrontierAtomicCertificate
#check PeritextSided.StateGC.FrontierAtomicCertificate.settled
#check PeritextSided.StateGC.collectStableBase_render_preserved
#check PeritextSided.StateGC.frontier_collectStableBase_safe
#check PeritextSided.StateGC.frontier_delayed_references_kept
#check PeritextSided.StateGC.collectStableBase_twoEpoch
#check PeritextSided.ProductionCertificate
#check PeritextSided.productionCertificate
#check PeritextSided.ProductionCertificate.interactionWF
#check PeritextSided.ProductionCertificate.interactionRefines
#check PeritextSided.ProductionCertificate.interactionQueries
#check PeritextSided.ProductionCertificate.interactionRefinesV
#check PeritextSided.ProductionCertificate.interactionQueriesV
#check PeritextSided.ProductionCertificate.virtualRepairReady
#check PeritextSided.ProductionCertificate.headOnlyVirtualMerge
#check PeritextSided.Interaction.fetchResult_virtualMerge_ready
#check PeritextSided.Interaction.HeadOnlyMergeCertificate.related
#check PeritextSided.Interaction.MaterializationDelta.headOnlyMergeInstall
#check PeritextSided.production_localRichIntent
#check PeritextSided.Interaction.StateRel
#check PeritextSided.Interaction.StateRel.snapshot
#check PeritextSided.Interaction.StateRel.compactInsertOp_exact
#check PeritextSided.Interaction.StateRel.textProjection_apply
#check PeritextSided.Interaction.sMergeL_filter
#check PeritextSided.Interaction.CommonProjectionFrame.merge_text_exact
#check PeritextSided.Interaction.translateText_exact
#check PeritextSided.Interaction.commonProjectionFrame_of_epochs
#check PeritextSided.Interaction.merge_text_after_epoch_translation
#check PeritextSided.Interaction.MergeCoverageCertificate
#check PeritextSided.Interaction.PhysicalMergeEvidence
#check PeritextSided.Interaction.PhysicalMergeEvidence.toCoverage
#check PeritextSided.Interaction.PhysicalMergeEvidence.of_sources
#check PeritextSided.Interaction.StateRelAt.merge
#check PeritextSided.Interaction.osMergeL_eq_union
#check PeritextSided.Interaction.osPayloads_union
#check PeritextSided.Interaction.InteractionGCCertificate
#check PeritextSided.Interaction.StateRel.collect
#check PeritextSided.Interaction.StateRelAt.collect
#check PeritextSided.Interaction.FrontierProjection.keep_future
#check PeritextSided.Interaction.FrontierProjection.andPlan
#check PeritextSided.Interaction.fresh_timestamp_need_not_exceed_frontier
#check CausalClockedAt
#check ClockedGuardedStep3
#check PeritextSided.Interaction.mintAfterFrontier_of_causalClock
#check PeritextSided.Interaction.StateRelAt.text_apply_after_frontier
#check PeritextSided.Interaction.ApplyEpochFrame.mintAfter
#check PeritextSided.Interaction.compactApply
#check PeritextSided.Interaction.render_projection
#check PeritextSided.Interaction.StateRelAt.render_with_marks
#check PeritextSided.Interaction.StateRelAt.mark_add
#check PeritextSided.Interaction.StateRelAt.delete_add
#check PeritextSided.Interaction.StateRelAt.text_insert
#check PeritextSided.Interaction.CompactApplyCertificate
#check PeritextSided.Interaction.StateRelAt.compact_apply
#check PeritextSided.Interaction.CombinedConfig.WellFormed
#check PeritextSided.Interaction.CombinedConfig.query_eq
#check PeritextSided.Interaction.fetchResult_wellFormed
#check PeritextSided.Interaction.commitGCResult_wellFormed
#check PeritextSided.Interaction.StateGCAction
#check PeritextSided.Interaction.StateGCAction.wellFormed
#check PeritextSided.Interaction.StateGCAction.semantic_stutters
#check PeritextSided.Interaction.MaterializationDelta
#check PeritextSided.Interaction.MaterializationDelta.introduced_isSome
#check PeritextSided.Interaction.SingleInstallFrame
#check PeritextSided.Interaction.MaterializationDelta.singleInstall
#check PeritextSided.Interaction.MaterializationDelta.compactApplyInstall
#check PeritextSided.Interaction.CombinedStep
#check PeritextSided.Interaction.CombinedStep.wellFormed
#check PeritextSided.Interaction.CombinedSteps
#check PeritextSided.Interaction.combinedSteps_refines_Step3
#check PeritextSided.Interaction.combinedTrace_query_eq

/-! Negative controls remain absent from this production package: BudgetCart
has no `VerifiedMRDT` witness, and Shesha's checked refutations live only in
the refutation modules. -/
