import Sal.ConditionedMRDTs.Metatheory.VerifiedMRDT
import Sal.ConditionedMRDTs.Metatheory.ContractReach
import Sal.ConditionedMRDTs.Metatheory.ContinuationEquivalence
import Sal.ConditionedMRDTs.Metatheory.AbstractJoin
import Sal.ConditionedMRDTs.Metatheory.SeparateJoinDoctrines
import Sal.ConditionedMRDTs.MRDT_Instances.EmbedRGA.EmbedRGA
import Sal.ConditionedMRDTs.MRDT_Instances.Shesha.Shesha_Presplice_Refuted
import Sal.ConditionedMRDTs.MRDT_Instances.RGA_Rehoming.RGA_SeqSpec_Refuted
import Sal.ConditionedMRDTs.MRDT_Instances.Peritext_Embed.PeritextEmbed_MarksGC_A3
import Sal.ConditionedMRDTs.Refutations.SiblingSplice_Fooling

/-! A mechanically checked ledger for the consolidation interfaces. -/

open Sal.ConditionedMRDTs

#check ContractReach.invariant
#check contractReach3_iff_honestReach
#check contractReach3V_iff_honestReachV
#check joinKitAt_plain_iff
#check joinKitAt_witness_iff
#check abstractJoinAt_core_iff
#check abstractJoinAt_witness_iff
#check abstractJoinAt_arb_iff
#check observationalJoinAt_eqH_iff
#check coherentWitnessJoinAt_iff
#check GenHonest.exists_causalFold
#check WorldCompaction.observe_compactSeq_collapse
#check StabilityEpochFamily.multiEpoch_reads
#check SequentialRefinement.run
#check SequentialRefinement.prod
#check VerifiedMRDT.ra_linearizable
#check VerifiedMRDT.prod
#check VerifiedRuntimeMRDT.compact_continuation
#check ContinuationRepresentation.encode_ne_of_distinguishing
#check ContinuationRepresentation.encode_injective_of_pairwise_distinguishable
#check ContinuationRepresentation.card_history_le_repr
#check ContinuationRepresentation.card_history_le_two_pow_bits
#check ContinuationFoolingPair.lowerBound
#check e_join_kit_at
#check Sal.ConditionedMRDTs.SheshaPrespliceCX.shesha_join_kit_at_eff_refuted
#check SiblingSpliceFooling.sibling_splice_retention_lower_bound
#check RGA_TF_SeqSpec.rehoming_sequential_representation_lower_bound
#check PeritextEmbed.MarksGC.SPOT_A3.alpha_pair_retention_lower_bound
