import Sal.MRDTs.Framework.StateGC
import Sal.MRDTs.Instances.GSet
import Sal.MRDTs.Instances.BoundedCounter
import Sal.MRDTs.Instances.RGA
import Sal.MRDTs.Instances.MVR
import Sal.MRDTs.Instances.QueueCertificates
import Sal.MRDTs.Instances.ProductionRGA
import Sal.MRDTs.Instances.FugueMaxRALinearization
import Sal.MRDTs.Instances.Peritext
import Sal.MRDTs.GC.Refinement
import Sal.MRDTs.GC.StateComposition

/-! Build gate for the plain-signature reconstruction. -/

namespace Sal.MRDTs

#check MRDTSig
#check Configuration
#check initConfig
#check Step
#check VirtualLCAResolver
#check canonicalVirtualLCA
#check StoreInv
#check lca_events_of_storeInv
#check storeInv_reachable
#check storeInv_reachableV
#check mca_events_cover
#check ra_linearizable3_of_join
#check ra_linearizable3V_of_join
#check StepV
#check GenerationContract
#check MintCertifiedReach
#check MintCertifiedReachV
#check SafetyCertificate
#check SequentialRefinement
#check ConvergenceCertificate
#check VerifiedMRDT
#check StateGCCertificate
#check StateGCProtocol
#check StateGCProtocol.refines
#check HeadOnlyMergeCapability
#check GC.Certificate
#check GC.Certificate.ofMCAClosed
#check GC.root_absent_when_dropped
#check GC.execution_refines_noGC
#check GC.runtime_refines_core
#check GC.runtime_refines_coreV
#check GC.combinedProtocol
#check GC.CombinedSteps.refinesV
#check GC.CombinedSteps.refinesRaw

#check Instances.GSet.generation
#check Instances.GSet.sequential
#check Instances.GSet.safety
#check Instances.BoundedCounter.BC
#check Instances.BoundedCounter.BC_coreVCs3
#check Instances.BoundedCounter.ra_linearizable
#check Instances.BoundedCounter.bcApplicable
#check Instances.BoundedCounter.bc_safetyStep
#check Instances.BoundedCounter.versions_safe
#check Instances.BoundedCounter.versions_safeV
#check Instances.BoundedCounter.sequential
#check Instances.BoundedCounter.verified
#check Instances.RGA.applicable
#check Instances.RGA.HistoryOK
#check Instances.RGA.convergence
#check Instances.RGA.sequentialSound
#check Instances.RGA.verified
#check Instances.MVR.mvrApplicable
#check Instances.MVR.mvr_seq_sound
#check Instances.MVR.verified
#check Instances.Queue.qApplicable
#check Instances.Queue.q_join_at
#check Instances.Queue.queue_seq_sound
#check Instances.Queue.verified
#check Instances.EmbedRGA.generation
#check Instances.EmbedRGA.convergence
#check Instances.SidedEmbedRGA.generation
#check Instances.SidedEmbedRGA.convergence
#check Instances.SidedEmbedRGA.sFold_liftOp
#check Instances.SidedEmbedRGA.sided_fold_subtree_convex
#check Instances.SidedEmbedRGA.fuguemax_same_origin_low_first
#check Instances.SidedEmbedRGA.fuguemax_forward_ni
#check Instances.SidedEmbedRGA.fuguemax_backward_ni
#check Instances.SidedEmbedRGA.fuguemax_maximally_noninterleaving
#check Instances.SidedEmbedRGA.fApplicable
#check Instances.SidedEmbedRGA.fmGeneration
#check Instances.SidedEmbedRGA.fmConvergence
#check Instances.SidedEmbedRGA.fuguemax_ra_linearizable
#check Instances.ProductionRGA.embed
#check Instances.ProductionRGA.sided
#check Instances.Peritext.verified
#check Instances.Peritext.render_sequentially_correct
#check VerifiedMRDT.converges
#check VerifiedMRDT.convergesV
#check VerifiedMRDT.sequentially_correct

example (D : MRDTSig) : Configuration D := initConfig D

end Sal.MRDTs
