import Sal.MRDTs.Framework.StateGC
import Sal.MRDTs.Framework.Product
import Sal.MRDTs.Instances.GSet
import Sal.MRDTs.Instances.AddStore
import Sal.MRDTs.Instances.FlatCounters
import Sal.MRDTs.Instances.FlatGrowOnly
import Sal.MRDTs.Instances.BoundedCounter
import Sal.MRDTs.Instances.RGA
import Sal.MRDTs.Instances.RGASequential
import Sal.MRDTs.Instances.MVR
import Sal.MRDTs.Instances.QueueCertificates
import Sal.MRDTs.Instances.QueueConditioningSPOT
import Sal.MRDTs.Instances.ProductionRGA
import Sal.MRDTs.Instances.FugueMaxRALinearization
import Sal.MRDTs.Instances.FugueForward
import Sal.MRDTs.Instances.FuguePolicyGC
import Sal.MRDTs.Instances.Peritext
import Sal.MRDTs.Instances.SidedPeritext
import Sal.MRDTs.Instances.PeritextRenderGC
import Sal.MRDTs.Instances.PeritextMarkPairGC
import Sal.MRDTs.Instances.SidedPeritextStateGC
import Sal.MRDTs.Instances.SidedPeritextInteraction
import Sal.MRDTs.Instances.SidedPeritextProtocol
import Sal.MRDTs.Instances.TreeMove
import Sal.MRDTs.Instances.TreeMoveGC
import Sal.MRDTs.Instances.AegisSheetGC
import Sal.MRDTs.Instances.AegisSheetSequential
import Sal.MRDTs.Instances.InteractionSPOT
import Sal.MRDTs.GC.Refinement
import Sal.MRDTs.GC.StateComposition

/-! Build gate for the plain-signature reconstruction. -/

namespace Sal.MRDTs

#check MRDTSig
#check Configuration
#check initConfig
#check Step
#check VirtualLCAResolver
#check canonicalVirtualLCA
#check StoreInv
#check lca_events_of_storeInv
#check storeInv_reachable
#check storeInv_reachableV
#check mca_events_cover
#check ra_linearizable3_of_join
#check ra_linearizable3V_of_join
#check StepV
#check Issuance
#check MintCertifiedReach
#check MintCertifiedReachV
#check MintCertifiedReach.toV
#check SafetyCertificate
#check SafetyCertificate.preservation
#check SequentialRefinement
#check SequentialSpec
#check InteractionSpec
#check interactionLoOn
#check ConvergenceCertificate
#check ConvergenceCertificate.sound
#check VerifiedMRDT
#check ReplayVerifiedMRDT
#check IsSpecRALinearizable
#check Instances.InteractionSPOT.LWW.old_no_chain_refuted
#check StateGCCertificate
#check StateGCProtocol
#check prodSig
#check applySeq_prod
#check StateGCProtocol.refines
#check HeadOnlyMergeCapability
#check Instances.SidedPeritext.StateGC.Protocol.protocol
#check Instances.SidedPeritext.StateGC.Protocol.refines
#check Instances.SidedPeritext.StateGC.Protocol.Represents.collectText
#check Instances.SidedPeritext.StateGC.Protocol.Represents.trimDeleted
#check Instances.SidedPeritext.StateGC.Protocol.Represents.dropMarkPair
#check GC.Certificate
#check GC.Certificate.ofMCAClosed
#check GC.EvidenceSPOT.complete
#check GC.EvidenceSPOT.missing_author
#check GC.root_absent_when_dropped
#check GC.execution_refines_noGC
#check GC.runtime_refines_core
#check GC.runtime_refines_coreV
#check GC.combinedProtocol
#check GC.CombinedSteps.refinesV
#check GC.CombinedSteps.refinesRaw

#check Instances.GSet.generation
#check Instances.GSet.sequential
#check Instances.GSet.safety
#check Instances.GSet.verified
#check Instances.FlatCounters.counterVerified
#check Instances.FlatCounters.iocVerified
#check Instances.FlatCounters.pnVerified
#check Instances.FlatGrowOnly.gosetVerified
#check Instances.FlatGrowOnly.gomapVerified
#check Instances.BoundedCounter.BC
#check Instances.BoundedCounter.BC_coreVCs3
#check Instances.BoundedCounter.ra_linearizable
#check Instances.BoundedCounter.bcApplicable
#check Instances.BoundedCounter.bc_safetyStep
#check Instances.BoundedCounter.versions_safe
#check Instances.BoundedCounter.versions_safeV
#check Instances.BoundedCounter.sequential
#check Instances.BoundedCounter.verified
#check Instances.RGA.applicable
#check Instances.RGA.HistoryOK
#check Instances.RGA.convergence
#check Instances.RGA.sequentialSound
#check Instances.RGA.verified
#check Instances.RGA.replayVerified
#check Instances.RGA.listSpec
#check Instances.RGA.rga_spec_linearizable
#check Instances.RGA.rga_spec_linearizableV
#check Instances.MVR.mvrApplicable
#check Instances.MVR.mvr_seq_sound
#check Instances.MVR.replayVerified
#check Instances.MVR.concurrentState_no_sequential_register
#check Instances.Queue.qApplicable
#check Instances.Queue.q_join_at
#check Instances.Queue.queue_seq_sound
#check Instances.Queue.replayVerified
#check Instances.Queue.ConditioningSPOT.duplicate_dequeue_not_fifo
#check Instances.TreeMove.applicable
#check Instances.TreeMove.render_safe
#check Instances.TreeMove.join
#check Instances.TreeMove.sequentialSound
#check Instances.TreeMove.selfMove_rejected
#check Instances.TreeMove.verified
#check Instances.TreeMove.GC.undoRedo_algorithm_refines
#check Instances.TreeMove.GC.collectPrefix_exact
#check Instances.TreeMove.GC.appendFresh_exact
#check Instances.TreeMove.GC.fullyStable_collectTrash_query
#check Instances.TreeMove.GC.protocol
#check Instances.TreeMove.GC.combinedProtocol
#check Instances.TreeMove.GC.refines
#check Instances.AegisSheet.applicable
#check Instances.AegisSheet.publishedMergeOutcome
#check Instances.AegisSheet.publishedUndoOutcome
#check Instances.AegisSheet.table4MoveInsertUndoState
#check Instances.AegisSheet.table4MoveMoveUndoState
#check Instances.AegisSheet.resolveRange
#check Instances.AegisSheet.join
#check Instances.AegisSheet.replayVerified
#check Instances.AegisSheet.GC.naive_collection_changes_future_observation
#check Instances.AegisSheet.GC.requires_semantic_marker
#check Instances.AegisSheet.GC.semanticCollect
#check Instances.AegisSheet.GC.eventTimes_semanticCollect
#check Instances.AegisSheet.GC.semanticCollect_idempotent
#check Instances.AegisSheet.GC.view_semanticCollect
#check Instances.AegisSheet.GC.semanticCollect_insert_normalized
#check Instances.AegisSheet.GC.semanticCollect_union_normalized
#check Instances.AegisSheet.GC.certificate
#check Instances.AegisSheet.GC.markerFromFrontier_has_roster
#check Instances.AegisSheet.GC.marker_preserves_late_restore_fixture
#check Instances.AegisSheet.Sequential.State
#check Instances.AegisSheet.Sequential.spec
#check Instances.AegisSheet.Sequential.step
#check Instances.AegisSheet.Sequential.view
#check Instances.AegisSheet.Sequential.Chronological
#check Instances.AegisSheet.Sequential.chronological_eq_of_toFinset_eq
#check Instances.AegisSheet.Sequential.inplaceStateRel
#check Instances.AegisSheet.Sequential.inplaceSequentialSound
#check Instances.AegisSheet.Sequential.inplaceSequential
#check Instances.AegisSheet.Sequential.inplaceReplayVerified
#check Instances.AegisSheet.Sequential.concurrent_origins_not_guarded_chronological
#check Instances.AegisSheet.sequentially_correct
#check Instances.AegisSheet.observationally_correct
#check Instances.EmbedRGA.generation
#check Instances.EmbedRGA.convergence
#check Instances.SidedEmbedRGA.generation
#check Instances.SidedEmbedRGA.convergence
#check Instances.SidedEmbedRGA.sFold_liftOp
#check Instances.SidedEmbedRGA.sided_fold_subtree_convex
#check Instances.SidedEmbedRGA.fuguemax_same_origin_low_first
#check Instances.SidedEmbedRGA.fuguemax_forward_ni
#check Instances.SidedEmbedRGA.fuguemax_backward_ni
#check Instances.SidedEmbedRGA.fuguemax_maximally_noninterleaving
#check Instances.SidedEmbedRGA.fApplicable
#check Instances.SidedEmbedRGA.fmGeneration
#check Instances.SidedEmbedRGA.fmConvergence
#check Instances.SidedEmbedRGA.fuguemax_ra_linearizable
#check Instances.SidedEmbedRGA.fugue_forward_ni
#check Instances.SidedEmbedRGA.FuguePolicyGC.liveGapChoose_exact
#check Instances.SidedEmbedRGA.FuguePolicyGC.liveGapParentChain_exact
#check Instances.SidedEmbedRGA.FuguePolicyGC.mergeRetainedGap_observation_reachable
#check Instances.SidedEmbedRGA.FuguePolicyGC.stable_dead_leaf_collection_changes_future_read
#check Instances.ProductionRGA.replayEmbed
#check Instances.ProductionRGA.replaySided
#check Instances.ProductionRGA.embed
#check Instances.ProductionRGA.sided
#check Instances.ProductionRGA.embedCanonical_seqOK
#check Instances.ProductionRGA.unrelated_insert_delete_not_raw_comm
#check Instances.Peritext.replayVerified
#check Instances.Peritext.render_sequentially_correct
#check Instances.AddStore.verified
#check Instances.FinsetStore.verified
#check Instances.PeritextRender.doc_no_backward_leak
#check Instances.SidedPeritext.coreGuard
#check Instances.SidedPeritext.coreHonest_of_mint
#check Instances.SidedPeritext.core_join_at
#check Instances.SidedPeritext.replayVerified
#check Instances.SidedPeritext.verified
#check Instances.SidedPeritext.sequentially_correct
#check Instances.SidedPeritext.RichCore
#check Instances.SidedPeritext.renderState
#check Instances.SidedPeritext.richReplayVerified
#check Instances.SidedPeritext.richVerified
#check Instances.SidedPeritext.rich_sequentially_correct
#check Instances.PeritextRender.GC.renderMarksDoc_dropDoc
#check Instances.PeritextRender.GC.renderMarksDoc_deleted_congr
#check Instances.PeritextRender.GC.a3_guarded_drop
#check Instances.SidedPeritext.StateGC.gapEntryOf_exact
#check Instances.SidedPeritext.StateGC.compactInsertOp_exact
#check Instances.SidedPeritext.StateGC.collectText_query_preserved
#check Instances.SidedPeritext.StateGC.stableCut_mono_collectText
#check Instances.SidedPeritext.StateGC.dropped_below_stableCut
#check Instances.SidedPeritext.StateGC.TextPlan.keeps_fresh
#check Instances.SidedPeritext.StateGC.fresh_above_stableCut
#check Instances.SidedPeritext.StateGC.applySeq_s_filter
#check Instances.SidedPeritext.StateGC.textContOK_of_epoch
#check Instances.SidedPeritext.StateGC.collectedText_continuation_query
#check Instances.SidedPeritext.StateGC.trimDeleted_query_preserved
#check Instances.SidedPeritext.StateGC.dropMarkPair_query_preserved
#check Instances.SidedPeritext.StateGC.Interaction.sMergeL_filter
#check Instances.SidedPeritext.StateGC.Interaction.EpochProjection.keeps_fresh
#check Instances.SidedPeritext.StateGC.Interaction.merge_text_after_epoch_translation
#check VerifiedMRDT.converges
#check VerifiedMRDT.convergesV
#check ReplayVerifiedMRDT.sequentially_correct

example (D : MRDTSig) : Configuration D := initConfig D

end Sal.MRDTs
